package andjelka.kvizpliz;

public class Questions {

    public String mQuestions[]={
            "Čime se bavi felinolog?",
            "Kada je osnovana SHS?",
            "Ko je agnostik?",
            "Ko je osnovao kompaniju Microsoft?",
            "U kojim jedinicama se izražava magnetna indukcija?",
            "Koja je najveća evropska luka po prometu?",
            "U sastav RNK ulaze?",
            "Afekti su emocionalni doživljaji koji su:",
            "Sn je hemijski simbol?",
            "Ko je autor pesme 'Santa Maria della Salute'?",
            "Ko peva pesmu 'Oči jedne žene'?",
            "Statički deo memorije, koji može samo da se čita, označava se kao: ",
            "Šta je JVM?",
            "Ko tumači lik Harijevog kuma u filmu 'Harry Potter'?",
            "Ko je komponovao 'Odu radosti'?",
            "Čiji lik se nalazi na novčanici od 1000 dinara?",
            "Adolescencija je:",
            "Koji glumac nije igrao u filmu Maratonci trce pocasni krug?",
            "NATO savez je:",
            "Koliko iznosi dužina staze za maratonsku trku?",
            "Za koji fudbalski klub igra poljski fudbaler Robert Lewandowski?",
            "Kakvi su ireverzibilni procesi?",
            "Šta leči kardiolog?",
            "Koji broj na dresu nosi Miloš Teodosić?",
            "Maslinova grančica je simbol:",
            "Ko je osvojio Davis cup 2010. godine?",
            "Na Eurosongu 2004. godine Srbiju je predstavljao Željko Joksimovic sa pesmom:",
            "Koje godine je slovo H uvedeno u srpski jezik?",
            "Na poljskom kanapka, a na srpskom:",
            "Najmlađi šampion u formuli 1 je:",
            "Kakvu vlast ima vlada Republike Srbije?",
            "Najveca pustinja na Zemlji je:",
            "Koji slikar je kreirao logo za Chupa Chups?",
            "Grad Valjevo je sedište:",
            "Šta proučava ekologija?",
            "Legendarni nemački fudbaler Oliver Kahn igrao je na poziciji:",
            "Koliko traje jedna četvrtina u vaterpolo utakmici?",
            "U seriji Ubice mog oca, lik inspektora iz Odeljenja za krvne delikte tumači:",
            "Prvi zvučni film je:",
            "Nordeus je kompanija koja se bavi pravljenjem:",
            "Olimpijske igre 2016. godine održane su u:",
            "Koja zemlja je pobednik Eurosonga 2017. godine?",
            "Eutanazija je:",
            "Koliko iznosi jedan inch?",
            "U kojoj državi se nalazi najviše vulkana?",
            "Koji bend je osnovao Jimmy Page?",
            "Ko je napisao delo 'Gospodar prstenova'?",
            "Koje godine je Neil Armstrong sleteo na Mesec?",
            "Enolog je poznavalac:",
            "Kako se zove frontmen grupe The Rolling Stones?",
            "Rotonda označava:",
            "Šta je polihronija?",
            "Koji arhitekta je stvorio urbanističku koncepciju Novog Beograda?",
            "Šta su lagumi?",
            "Čime se hrani svilena buba?",
            "Šta je 'bela kuga?'",
            "Eros i Amor su jedan drugome:",
            "Koja vrsta gramofonskih ploča se vrti na 33 obrtaja?",
            "Prvi avion kompanije 'Air Serbia' nosi naziv:",
            "Koje mesto je zauzela muška košarkaška reprezentacija Srbije na Olimpijskim igrama 2016. godine?",
            "Pesmu 'Igraj i pobedi' izvodi grupa:",
            "Koje godine je izašao iPhone SE?",
            "Kako se zvao konj Aleksandra Velikog?",
            "Cogito, ergo sum ili?",
            "Izohaline su tačke koje spajaju mesta:",
            "Na nemačkom Kuplung, a na srpskom?",
            "Kapiten muške seniorske reprezentacije Srbije u košarci je?",
            "U kom gradu je rođen fudbaler Matija Nastasić?",
            "Stefan Uroš III Dečanski vladao je Srbijom:",
            "Ko igra glavnu ulogu u filmu 'Vrati se Zone'?",
            "Koji srpski vladar je ubijen na Košutnjaku?",
            "Ko je napisao pripovetku 'Kašika'?",
            "Kojoj FCI grupi pripada rasa pasa Labrador?",
            "U kom gradu u Italiji se nalazi katedrala Duomo?",
            "U kom sazvežđu se nalazi zvezda Severnjača?",
            "U kakvim su rodbinskim odnosima osnivači kompanija Puma i Adidas su?",
            "Slava grada Beograda je?",
            "Koliko dana posle Vaskrsa se obeležavaju Duhovi ili Trojice?",
            "Plavog jahača je naslikao?",
            "Nekada Lenjingrad, a danas?",
            "Pesmu 'Na dlanu' izvodi:",
            "Koji vitamin se nalazi u bademu?",
            "Kengur bez granica je međunarodno takmičenje u oblasti:",
            "Laufer ili?",
            "Koje boje je dragi kamen ametist?",
            "+49 je pozivni broj za:",
            "Koliko 1 bit ima bajta?",
            "U kom gradu se nalazi spomenik Stevanu Filipoviću?",
            "Kako se zove verni pratilac Snupija?",
            "Koliko puta je ženska rukometna reprezentacije Jugoslavije bila prvak sveta?",
            "U kom mesecu se obeležava svetski dan knjige?",
            "Gde se nalazi grad Retimno?",
            "Osoba X stane u red i spreda je peti, a otpozadi sedmi. Koliko ima ljudi u redu?",
            "Koji je službeni jezik u Gvajani?",
            "Kako se u fizici obeležava ubrzanje?",
            "Koja pevačica je sa Barbadosa?",
            "Koje godine je umrla Milena Pavlović Barili?",
            "U kom gradu je preminuo Leonardo da Vinči?",
            "Šta je australopitekus?",
            "Gde je nastao čartistički radnički pokret?",
            "Sajberfobija je strah od:",
            "Marjaš je:",
            "Koja od ponuđenih zemalja je najveća po površini?",
            "Koja je najtoplija planeta sunčevog sistema?",
            "Galerija Borgeze je jedan od najvećih muzeja:",
            "Uopštenje pitagorine teoreme je:",
            "Koji podvodni tunel je najduži na svetu?",
            "Ko je igrao glavnu ulogu u filmu 'Umri muški'?",
            "Koliko NBA titula je osvojio Michael Jordan?",
            "Ko je komponovao 'Na lepom plavom Dunavu'?",
            "Kakve konje je želeo Vasa Ladački u pesmi Đorđa Balaševića",
            "John Cena je profesionalni američki:",
            "Ko igra glavnu ulogu u filmu 'Jesen Samuraja'?",
            "Koliko ima horoskopskih znakova?",
            "U crtanom filmu 'Pingvini sa Madagaskara' jedan pingvin ima isto ime kao i čin u vojsci, a to je:",
            "Koje godine je osnovana banka Intesa Beograd?",
            "Tajni agent Izzy ima ptičicu pomagača koja se zove:",
            "Iz koje godine je film 'Pirati silikonske doline'?",
            "Kako se zove organizacija slična Crvenom krstvu u muslimanskim zemljama?",
            "Koliko je visok oblakoder Beograđanka?",
            "Kako se zove najveći svetski proizvođač rajsferšlusa?",
            "Oto Hajnrih Varburg je bio nemački:",
            "Koji od ovih instrumenata čine ritam sekciju?",
            "Nauka o krvi ili:",
            "Kojoj crkvi je Laza Kostić posvetio pesmu 'Santa Maria della Salute'?",
            "Rod Blagojević, američki političar srpskog porekla, bio je guverner:",
            "Gde se nalazi grad Retimno?",
            "Koje godine je umro poznati modni kreator Iv Sen Loran?",
            "Simbol otmenosti i carske vlasti u Japanu je:",
            "Gde se odvija radnja opere 'Karmen'?",
            "Pol Alen je 1975. godine postao suosnivač:",
            "Aleksandar Litvijenko, bivši potpukovnik KBG-a, je 2006. godine izgubio život nakon:",
            "Koje godine je sagrađena i puštena u rad prva termoelektrana?",
            "Predgrađe kog grada predstavlja Grinič (Nulti meridijan)?",
            "Oziris je bio egipatski bog:",
            "Ko je bio selektor fudbalske reprezentacije Srbije pre Radomira Antića?",
            "Film 'Vreme čuda' režirao je:",
            "Koja materija je najtvrđa od navedenih?",
            "Ko peva pesmu 'Sviraj brate'?",
            "Koje je nacionalno piće Poljske?",
            "Koja od ovih zemalja nije bila u sastavu Beneluksa?",
            "Kako se zvao dinosaurus ptica?",
            "Ekstenzija .txt označava?",
            "Grip H1N1 poznatiji je kao?",
            "Ime Ivan je poreklom iz:",
            "Kako se zove mitološko čudovište u kojem su sjedinjeni lav i orao?",
            "Ko je 395. godine podelio Rimsko carstvo na zapadno i istočno?",
            "Šta je Venerikina kosa?",
            "Koja je prva zemlja od 01.01.2002. godine legalizovala eutanaziju?",
            "Gde se nalazi Legoland?",
            "Za koji sport je nadležna FINA?",
            "Kako se zove atletičar kome je 1998. oduzeta zlatna medalja i poništen rekord na 100 metara?",
            "Od koga je Goran Ivanišević izgubio svoje prvo finale Wimbledona?",
            "Scipion Afrički je pobedio Hanibala kod Zame zahvaljujući:",
            "Ako si imao 89 riba i trećina se udavi, a ti dodaš petinu novodobijenog broja, koliko riba sada imaš?",
            "Koliko je lne?",
            "Šta je Viminacijum?",
            "Koji je najveći trocifren broj deljiv sa 3?",
            "Koja je najmanja država na svetu?",
            "Koji je najviši planinski vrh u Srbiji?",
            "Kako se zove veština lepog i urednog pisanja",
            "Gde se nalazi ostrvo Vido?",
            "Prvo sedište nezavisne srpske patrijaršije je:",
            "Ko je pobedio minhenski Bayern Münich u finalu fudbalske Lige Šampiona za sezonu 2012/13?",
            "Autor romana 'Bornov identitet' je:",
            "Koja od sledećih država nije transkontinentalna?",
            "Ko je režirao filmski hit 'Avatar'?",
            "Za koju oblast je danski naučnik Nils Bor dobio Novelovu nagradu?",
            "Koje godine je osnovana muzička akademija u Beogradu?",
            "Kleopatra, kraljica poznata po svojoj mudrosti i lepoti, vladala je:",
            "Koji je naziv za poglavara katoličke crkve?",
            "Kopnena zona bezbednosti se nalazi duž administrativne linije republike Srbije sa:",
            "Ko je bio otac Urošu Nejakom?",
            "Koje je pravo ime poznate američke pevačice Lady Gage?",
            "Nauka o oblicima je:",
            "Ko je oslobodio Tezeja iz Hada?",
            "Glavni sastojak skorupa je:",
            "Šta znači jurisdikcija?",
            "Ko je policajac sa Beverli Hilsa?",
            "Gde je održan završni turnir košarkaške Evrolige za 2013. godinu?",
            "U kom delu sveta se nalazi država Jemen?",
            "Koji od navedenih glumaca nije nagrađen Oskarom?",
            "Koliko boja se nalazi na zastavi Granade?",
            "Pre izgradnje crkve Svetog Petra u Rimu, najveća hrišćanska crkva na svetu bila je:",
            "Gde je rođen Oskar Davičo?",
            "Koju grupu je osnovao basista Dušan Kojić - Koja?",
            "U kom zalivu se nalazi ostrvo na kom je umro Napoleon I Bonaparta?",
            "Šta je tanah?",
            "Šta je pesonata?",
            "Poznata igra 'PES' je najpoznatija simulacija?",
            "Šta je Singidunum?",
            "Nikolaj Rimski Korsakov bio je:",
            "Koje su osnovne boje?",
            "Konveksan znači:",
            "Ko izvodi pesmu 'Dirli, dirli, dirlija'?",
            "Šta je ebola?",
            "Sony je kompanija iz:",
            "Gde je održano Svetsko prvenstvo u fudbalu 2010. godine?",
            "Za koji klub je do maja 2018. igrao španski fudbaler Andrés Iniesta Luján?",
            "Iz koje zemlje je pobednik Eurosonga 2018. godine?",
            "Koje godine se održalo prvo Svetsko prvenstvo u fudbalu?",
            "Koliko je dece imao Stefan Uroš I?",
            "Koje godine je osnovana kompanija 'Frikom'?",
            "Koliko dece ima britanski princ Vilijam?",
            "Koja zemlja je poznata po ružama?",
            "Za koji košarkaški tim igra Kyrie Irving?",
            "Gde se nalazi zabranjeni grad?",
            "Šta je akreditiv?",
            "Koje godine je osnovana kompanija Knjaz Miloš?",
            "Ko glumi Damira Fazlinovića u seriji 'Lud, zbunjen, normalan'?",
            "Na kom ostrvu je preminuo Napoleon Bonaparta?",
            "Dopunite naziv pesme Plavog orkestra. Lovac i?",
            "Kako se zove predsednik SAD?",
            "Ko se smatra ocem istorije?",
            "Koliko godina ima Julija u Šekspirovoj drami 'Romeo i Julija'?",
            "U kom manastiru na Svetoj gori se zamonašio Rastko Nemanjić?",
            "Džastin Frankel je osmislio:",
            "Biljka Šumarica je?",
            "Šta je Kaspersky?",
            "DJ je?",
            "Sa kojim državama se graniči republika Nikaragva?",
            "Ko je snimio album 'Kind of Blue'?",
            "Na kom kontinentu se nalazi Gvajana?",
            "Ko je napisao naučno-fantastični roman 'Nineteen eighty-four (1984)'?",
            "U kom klubu je David Backham završio karijeru?",
            "Koje životinje predu osim mačaka?",
            "Koja država je prva počela da koristi papirne novčanice?",
            "Koja je najveća životinja na svetu?",
            "Glavni grad Kolumbije je?",
            "Nekada se zvala Burma, o kojoj državi je reč?",
            "Kako se zvao Muhammed Ali pre nego što je promenio ime?",
            "U kojoj državi se nalazi Angkor Wat, najveći religijski hram na svetu?",
            "Pre nego što je započeo solo karijeru Sting je bio glavni tekstopisac, basista i pevač jedne rok grupe. O kojoj grupi je reč?",
            "Machu Picchu je sveti grad kog drevnog naroda?",
            "Gde se nalazi Mikronezija?",
            "Čega se plaše akrofobični ljudi?",
            "U kom romanu britanskog pisca Iana Fleminga se prvi put pojavio James Bond?",
            "U kom gradu se nalazi Bazilika sv. Marka?",
            "Ko je nasledio kneza Miloša na čelu Srbije 1839. godine?",
            "Dobitnik FIFA nagrade za najboljeg fudbalera 2018. godine je?",
            "Gde se nalazi planina Kilimandžaro?",
            "Kroz koji grad protiče reka Neva?",
            "Ko je napisao 'Za kim zvona zvone'?",
            "U kojoj državi je rođen Adolf Hitler?",
            "Ksenofobija je strah od?",
            "Glavni grad Nepala je:",
            "Iz kog jezika potiče reč juvelir?",
            "Izvođač pesme 'Piješ sine' je?",
            "Izbacite uljeza:",
            "U seriji 'Nemanjići - rađanje kraljevine' lik druge supruge Stefana Prvovenčanog tumači?",
            "Osveta je jelo koje se servira...?",
            "Kada neko igra fudbal žinga (ginga) stilom, on je verovatno iz?",
            "Šta je Natalijina Ramonda?",
            "Ko je otkrio Lepenski vir?",
            "Koje godine se odigrala bitka kod Tanenberga?",
            "Paul Klee se proslavio kao?",
            "Kom slivu pripada reka Drina?",
            "'Brankovo kolo' je dobilo ime po pesniku Branku:",
            "Ko je napisao pripovetku 'Sve će to narod pozlatiti'?",
            "Koga je ubio Jack Ruby?",
            "Koja država je kolevka sladoleda?",
            "Koje godine je napravljen prvi kornet?",
            "Kada je napravljen prvi sladoled na štapiću?",
            "Koji padež odgovara na pitanja 'koga, šta'?",
            "Koja od sledećih država nije članica EU?",
            "Kojom zemljom je vladao Vlad III Cepeš?",
            "Koliko ima krugova pakla u delu Dantea Aligijerija 'Božanstvena komedija'?",
            "Koje životinje predu osim mačaka?",
            "Glavni grad EU je?",
            "Šta su ligature?",
            "Koje godine je preminuo Fidel Kastro?",
            "Koja krvna grupa je univerzalni davalac?",
            "Radetzky marš napisao je?",
            "Ko igra glavnu mušku ulogu u filmu 'Kazablanka'?",
            "Glavna glumica u filmu 'Kazablanka' je?",
            "Drugi deo kog filmskog serijala je poznat pod nazivom 'Drumski ratnik'?",
            "Askja, Hekla i Katla su imena islandskih?",
            "Kako se zove album Dina Dvornika iz 1993. godine?",
            "Šta je kod Czeslawa Milosza zarobljeno, a kod Imanuela Kanta čisto i praktično?",
            "Bacil je bakterija kog oblika?",
            "Kako se zove žabac u komediji 'The Muppets'?",
            "Sa kojom pesmom je grupa 'Novi fosili' na Evroviziji 1987. godine osvojila 4. mesto?",
            "Anglofobija je strah od?",
            "Koji junak je poznat kao 'Zmaj od Noćaja'?",
            "Koje godine je otkrivena planeta Uran?",
            "Za koji od ponuđenih timova nikada nije igrao Ferenc Puskás?",
            "Koje godine je Stefan Nemanja otišao na Svetu Goru?",
            "Koje je nacionalno piće Kube?",
            "Potamologija je nauka o?",
            "Koji jezik se govori na Kubi?",
            "U kojoj još grupi je svirao Koja iz 'Discipline kičme'?",
            "Kako se zove košarkaš koji je 1992. godine u dresu Partizana postigao odlučujuću trojku za Kup šampiona?",
            "Kojoj državi pripada ostrvo Lanzarote?",
            "Koji od sledećih hemijskih elemenata se ne nalazi u sastavu limunske kiseline?",
            "Šta je po zanimanju bio Vasa Pelagić?",
            "Kako se naziva sila koja predstavlja delovanje dve ili više sila?",
            "Koliko godina je trajalo II fracusko carstvo?",
            "Kroz koju državu protiče reka Jenisej?",
            "Ko je šesta zvezdina zvezda?",
            "Šta je oskoruša?",
            "Koje godine je rođen Zvonko Bogdan?",
            "Do koliko stepeni može biti visoka temperatura na mestu električnog pražnjenja u atmosferi?",
            "Ono što je za Rim bio Koloseum, za Carigrad je?",
            "Najveća riba na svetu je?",
            "Koje boje je planeta Mars?",
            "Kako se stručno naziva zaštitnik prava građana?",
            "Mačkov kamen je najviši vrh jedne planine. O kojoj planini je reč?",
            "Koliko žica ima akustična gitara?",
            "Koliko dana je trajala Pariska komuna?",
            "Koja reka protiče kroz Grdeličku klisuru?",
            "Izbacite marku koja ne pripada istoj kompaniji.",
            "Šta u predvodu sa latinskog znači 'Una hirunda non facit ver'?",
            "Koja od navedenih čokoladica u sebi sadrži keks?",
            "Dovršite naziv benda: Nick Cave and?",
            " 'Nisam se oženio baš zato što cenim žene' rečenica je koju je izgovorio poznati filozof?",
            "Neologizam je?",
            "Šta je po zanimanju bio Loius Armstrong?",
            "Koji od sledećih gradova se ne nalazi na pruzi Beograd-Bar?",
            "Danilo Nikolić je poznati?",
            "Kako se naziva verovanje u boga u racionalnom smislu, bez vezivanja za određenu religiju?",
            "Kada je Kraljevina Jugoslavija pristupila Trojnom paktu?",
            "Na kom brodu je propisana kapitulacija Japana u Drugom svetskom ratu?",
            "Koja od sledećih grupa ostrva se ne nalazi u Indijskom okeanu?",
            "Mesto gde je Isus razapet je?",
            "Drugi naziv za nevoljno drhtanje tela je?",
            "'Sve iz inata' hit je grupe?",
            "Pozivni broj za Negotin je?",
            "Niz koji ima graničnu vrednosti je?",
            "U kom sportu se proslavio Momir Petković?",
            "Gde živi jedina vrsta slatkovodne foke na svetu?",
            "Konačni poraz Napoleona kod Vaterloa dogodio se?",
            "Ko je izgovorio 'Eureka!'?",
            "Kako se zvao čovek za kog se udala Jacqueline Kennedy nakon atentata na supruga?",
            "Šta je po veroispovesti bio Mohandas Karamchand Gandhi?",
            "Glavni grad američke savezne države Illinois je?",
            "Kada se odigrala Borodinska bitka?",
            "Koji od sledećih astroloških zankova pripada grupi zemljanih?",
            "Šta je kuglof?",
            "Koji kolumbijski pevač je pevao na otvaranju Mundijala 2010. godine u Južnoj Africi?",
            "Koliki je maksimalan broj rundi u profesionalnom boks meču?",
            "Kozaci su bili upamćeni kao konjanici koji su ratovali za interese?",
            "Na kom univerzitetu je predavao Mihajlo Pupin?",
            "Kako se zove slikar koji je naslikao plakat za film 'Bitka na Neretvi'?",
            "Koje nacionalnosti je tvorac Rubikove kocke?",
            "Prvi album pevačice Adele je?",
            "Ko je pravio violine?",
            "Odakle je pisac i istoričar Mikhaēl Psellos?",
            "Édson Arantes do Nascimento ili?",
            "Sposobnost nekog tela da vrši rad u fizici se naziva?",
            "Koliko je trajao let Challengera 1986. godine?",
            "Organizacija za obrazovanje, kulturu i nauku pod okriljem UN zove se?",
            "Šta je anekumena?",
            "Čuma je narodni naziv za koju bolest?",
            "Ko se budi u pesmi Šarla Akrobate?",
            "Koje godine je počela sa radom hidroelektrana Zvornik?",
            "Za koji italijanski klub je igrao Maradona?",
            "U kom mestu je rođen Adolf Hitler?",
            "Emetofobija je strah od?",
            "Koje je pravo ime strip junaka Zagora?",
            "Koje godine se Bangladeš otcepio od Pakistana?",
            "U kojoj saveznoj američkoj državi se nalazi San Francisco?",
            "Akvavit je?",
            "Koliko iznosi napon u evropskim električnim mrežama?",
            "Babin zub se nalazi u blizini?",
            "1/tangens ili?",
            "Čija je pesma 'Devojka iz grada'?",
            "Koji instrument je svirao Željko Joksimović pre nego što je počeo da peva i komponuje?",
            "Za najboljeg igrača EP u košarci 2007. godine proglašen je?",
            "Koje godine je izmišljen tranzistor?",
            "Koji je prvi srpski zvučni film?",
            "Šta je dženaza?",
            "Kako se zvala rimska boginja zemljoradnje?",
            "Koje je bilo svetovno ime Dositeja Obradovića?",
            "Ko je napisao knjigu 'Psihopatologija svakodnevnog života'?",
            "Kako se naziva mehanizam koji omogućava biljci da rastvorene hranljive materije iz zemlje dovede do lista?",
            "Kako se ranije zvao Zimbabve?",
            "Kako se zove glumica koja tumači glavnu ulogu u filmu 'Resident Evil'?",
            "Šta je bobija?",
            "Koja od navedenih reka nije pritoka Save?",
            "Šta je bodorka?",
            "Benjamin Disraeli je bio čuveni engleski?",
            "U kom gradu se igralo finale Lige Šampiona u fudbalu 2009. godine?",
            "Koje godine je preminuo Nikola Tesla?",
            "Koje od ponuđenih mora ima najveću brzinu?",
            "Gde je rođena makedonska pevačica Kaliopi Bukle?",
            "Koliko ima kičmenih pršljena?",
            "Koji fudbalski klub je proglašen za najbolji u XX veku?",
            "Koji film je dobio Oskara za najbolji film 2007. godine?",
            "Kom filozofu se pripisuje izreka 'Panta rei'?",
            "Falco peregrinus je?",
            "Trgovac na malo ili?",
            "Koja je najveća katolička zemlja na svetu?",
            "Koja ptica je nacionalni simbol u Indiji?",
            "Koliko puta je muška reprezentacija Srbije bila prvak Evrope u odbojci do 2014. godine?",
            "Ko je napisao roman 'U potpaljublju'?",
            "Radnja kog od navedenih filmova nije inspirisana istinitim događajem?",
            "Blizu kog grada se odigrala bitka na Čegru?",
            "Iz čijeg dela je lik Agaton?",
            "Koji naš bokser je osvojio zlatnu medalju u Moskvi 1980. godine?",
            "Čije telo je uzeto kao model za Zvončicu u filmu 'Petar Pan'?",
            "Koliko uglova ima deltoid?",
            "Ko je otkrio da je munja vrsta elektriciteta?",
            "Ko je prvi otkrio elektromagnetizam?",
            "Kako su vezani električni uređaji u domaćinstvu u električnom kolu?",
            "Koje je sveto drvo boga Peruna?",
            "Kako se zvao sveti bik Starih Egipćana?",
            "Koje dužine je bio Titanik?",
            "Ko je dobitnik Nobelove nagrade za književnost za 2012. godinu?",
            "Kako se naziva obezvređivanje novca koje se ogleda u padu kupovne moći novca?",
            "Pripovetka Ive Andrića je 'Aska i '?",
            "Telo se ravnomerno kretalo brzinom od 4 m/s. Koliko je kilometara prešlo ako se kretalo 25 sekundi?",
            "Ko od navedenih glumaca ne glumi u filmu 'Pretparačke priče' koji je režirao Quentin Tarantino?",
            "Šta je po zanimanju Rus Евге́ний Ива́нович Замя́тин (Jevgenij Zamjatin)?",
            "Kriks je?",
            "Koliko puta je pojavljuje cifra 9 u brojevima od 1 do 99?",
            "Šta znači izraz 'Pro bono'?",
            "Koji deo teritorije Srbije nije pripadao tzv. 'Staroj Srbiji'?",
            "Kada su u Srbiji uvedene obavezne metarske mere?",
            "Iz koje zemlje je čuveni astronom Christiaan Huygens?",
            "Šta označava reč 'ALVALUK'?",
            "'Mojsija' je izvajao?"


    };
    private String mChoices [] [] = {
            {"Proučavanjem mačaka", "Proučavanjem pasa", "Proučavanjem perja", "Proučavanjem lekovitih biljaka"},
            {"1914. godine", "1915.godine", "1918.godine", "1945.godine"},
            {"Nevernik", "Osoba koja pati od brojnih fobija", "Osoba koja nema pouzdanja u svoje znanje", "Osoba koja smatra da viša duhovna sila (božanstvo) možda postoji, ali da se ne može utvrditi oblik i priroda te sile"},
            {"Steve Jobs", "Bill Gates", "Lawrence (Larry) Page", "Mark Zuckerberg"},
            {"Tesla(T)", "Veber(Wb)", "Džul(J)", "Paskal(Pa)"},
            {"Roterdam", "Antverpen", "Marsej", "Hamburg"},
            {"Adenin, timin, citozin i guanin", "Adenin, citozin, guanin i uracil", "Adenin, citozin, uracil i timin", "Adenin, timin, guanin i uracil "},
            {"Slabi i dugotrajni", "Jaki i dugotrajni", "Slabi i kratkotrajni", "Jaki i kratkotrajni"},
            {"Antimon", "Stroncijum", "Kalaj", "Srebro"},
            {"Laza Kostić", "Aleksa Šantić", "Milan Rakić", "Dušan Vasiljev"},
            {"Miroslav Ilić", "Predrag Živković Tozovac", "Haris Džinović", "Šaban Šaulić"},
            {"RAM", "ROM", "Keš", "Buffer"},
            {"Java Visual Method", "Java Virtual Machine", "Java Visual Machine", "Java Virtual Method"},
            {"Geri Oldman", "David Thewlis", "Robbie Coltrane", "Alan Rickman"},
            {"Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Felix Mendelssohn", "Hector Berlioz"},
            {"Vuka Stefanovića Karadžića", "Ðorda Vajferta", "Nikole Tesle", "Jovana Cvijića"},
            {"Detinjstvo", "Zrelo doba", "Mladalačko doba", "Staračko doba"},
            {"Bogdan Diklić", "Bora Todorović", "Dragan Nikolić", "Zoran Radmilović"},
            {"Ekonomski savez", "Kulturni savez", "Vojni savez", "Politički savez"},
            {"42km", "35km", "22km", "32km"},
            {"TSV Bayer 04 Leverkusen", "Borussia Dortmund", "FC Bayern München", "KKS Lech Poznan"},
            {"Procesi koji se mogu kontrolisati", "Nepromenljivi procesi", "Kratkotrajni procesi", "Nepovratni procesi"},
            {"Bolesti srca", "Bolesti jetre", "Nasledne bolesti", "Bolesti pluća"},
            {"9", "4", "11", "5"},
            {"Mira", "Slobode", "Hrabrosti", "Pravde"},
            {"Francuska", "Češka", "Srbija", "Velika Britanija"},
            {"Nije ljubav stvar", "Lane moje", "Supermen", "Balada"},
            {"1834.", "1835.", "1836.", "1838."},
            {"Sendvič", "Čokolada", "Večera", "Posteljina"},
            {"Michael Schumacher", "Lewis Hamilton", "Sebastian Fetel", "Nico Rosberg"},
            {"Sudsku", "Izvršnu", "Zakonodavnu", "Vrhovnu"},
            {"Gobi", "Sahara", "Kalahari", "Velika pešcana pustinja"},
            {"Pablo Picasso", "Leonardo da Vinci", "Salvador Dali", "Francisco Goya"},
            {"Pčinjskog okruga", "Mačvanskog okruga", "Kolubarskog okruga", "Zlatiborskog okruga"},
            {"Životnu sredinu", "Insekte", "Poreklo reči", "Vina"},
            {"Veznog igrača", "Napadača", "Golmana", "Odbrambenog igrača"},
            {"10 minuta", "7 minuta", "8 minuta", "5 minuta"},
            {"Vuk Kostić", "Marko Janketić", "Tihomir Stanić", "Slavko Štimac"},
            {"Veliki diktator", "Pevač džeza", "Nevinost bez zaštite", "Svetla New Yorka"},
            {"Kompjuterskih igrica", "Antivirus programa", "Računarske opreme", "Pomoćnih programa"},
            {"Londonu", "Pekingu", "Tokiju", "Rio de Žaneiru"},
            {"Portugalija", "Australija", "Ukrajina", "Izrael"},
            {"Ubistvo iz nehata", "Ubistvo iz milosrđa", "Ubistvo iz koristoljublja", "Ubistvo iz osvete"},
            {"Oko 1cm", "Oko 2,5cm", "2,54cm", "Oko 5cm"},
            {"Japan", "Indonezija", "Meksiko", "Italija"},
            {"Led Zeppelin", "Queen", "Pink Floyd", "The Beatles"},
            {"Suzanne Collins", "J.R.R.Tolkien", "J.K.Rowling", "George R.R.Martin"},
            {"1959.", "1965.", "1969.", "1962."},
            {"Rakije", "Piva", "Viskija", "Vina"},
            {"Mick Jagger", "Michael Jordan", "Michael Jackson", "Jerry Lewis"},
            {"Silos", "Mlin", "Crkvu", "Cilindričnu građevinu"},
            {"Višeboj", "Višebojnost", "Grčka proročica", "Privremeno slepilo"},
            {"Milan Zloković", "Jan Nevole", "Nikola Dobrović", "Aleksej Brkić"},
            {"Podzemni prolazi ili prostorije", "Poluzatvoreni nadzemni prostori", "Zatvoreni prostori na osojnim padinama", "Prostorije na prirodno osunčanim prisojnim padinama"},
            {"Dudovim lišćem", "Smolom", "Lišajevima", "Larvama mrava"},
            {"Smanjenje nataliteta", "Smanjenje mortaliteta", "Porast nataliteta", "Porast mortaliteta"},
            {"Osiromašenje građana", "Unikat", "Pandan", "Sinonimi"},
            {"Ne postoji takva vrsta ploča", "Singl", "Extended play", "Long play"},
            {"Novak Đoković", "Vlade Divac", "Nikola Tesla", "Miki Manojlović"},
            {"Četvrto mesto", "Drugo mesto - srebro", "Treće mesto - bronza", "Prvo mesto - zlato"},
            {"Goša sa raskršća", "Beogradski sindikat", "THCF", "Neguj mo Srbski"},
            {"2016.", "2015.", "2017.", "2013."},
            {"Lamri", "Arnaut", "Rosinanta", "Bukefal"},
            {"Kocka je bačena", "Mislim, dakle postojim", "Dođoh, videh, pobedih", "U vinu je istina"},
            {"Iste nadmorske visine", "Istog pritiska", "Iste gustine vazduha, stena...", "Istog saliniteta"},
            {"Gas", "Kvačilo", "Brzina", "Kočnica"},
            {"Miloš Teodosić", "Milan Mačvan", "Nenad Krstić", "Stefan Marković"},
            {"U Obrenovcu", "U Beogradu", "U Valjevu", "U Šapcu"},
            {"Od 1282. do 1321. godine", "Od 1322. do 1331. godine", "Od 1331. do 1355. godine", "Od 1355. do 1371. godine"},
            {"Milan Vasić", "Vojin Ćetković", "Milan Lane Gutović", "Nikola Ristanovski"},
            {"Milan Obrenović", "Miloš Obrenović", "Aleksandar Obrenović", "Mihailo Obrenović"},
            {"Simo Matavulj", "Antonije Isaković", "Laza Lazarević", "Milovan Glišić"},
            {"VII", "VIII", "X", "IX"},
            {"U Rimu", "U Firenci", "U Veneciji", "U Milanu"},
            {"Mali medved", "Veliki medved", "Mala kola", "Veliki pas"},
            {"Otac i sin", "Deda i unuk", "Nisu u srodstvu", "Braća"},
            {"Trojice", "Sveta Petka", "Spasovdan", "Krstovdan"},
            {"30", "50", "10", "40"},
            {"Vasilij Kandinski", "Lovis Corinth", "Aleksej von Jawlensky", "August Macke"},
            {"Volgograd", "Sankt Peterburg", "Novgorod", "Belgorod"},
            {"OK band", "Tropico band", "Lapsus band", "Lexington band"},
            {"A", "D", "E", "B"},
            {"Matematike", "Fizike", "Hemije", "Informatike"},
            {"Top", "Lovac", "Skakač", "Pešak"},
            {"Tirkizne", "Ružičasto-crvene", "Plave", "Ljubičaste"},
            {"Francusku", "Nemačku", "Italiju", "Veliku Britaniju"},
            {"8", "1", "0", "12"},
            {"U Valjevu", "U Opuzenu", "U Mostaru", "U Kragujevcu"},
            {"Kalimero", "Tweety", "Gonzales", "Vudstok"},
            {"Tri puta", "Ni jednom", "Jednom", "Četiri puta"},
            {"U julu", "U aprilu", "U oktobru", "U decembru"},
            {"U Bugarskoj", "Na Kritu", "U Moldaviji", "U Rumuniji"},
            {"Četrnaest", "Dvanaest", "Trinaest", "Jedanaest"},
            {"Španski", "Engleski", "Portugalski", "Francuski"},
            {"S", "U", "T", "A"},
            {"Madonna", "Shakira", "Rihanna", "Beyonce"},
            {"1923.", "1945.", "1910.", "1961."},
            {"U Parizu", "U Rimu", "U Amboazu", "U Firenci"},
            {"Model automobila", "Vrsta hominida", "Arhaični jezik", "Vegetativni rod"},
            {"U Nemačkoj", "U SAD-u", "U Francuskoj", "U Velikoj Britaniji"},
            {"Belog luka", "Ljubljenja", "Kompjutera", "Samoće"},
            {"Metalni novac", "Nemirno dete", "Svirač", "Mađarski ples"},
            {"Mađarska", "Grčka", "Srbija", "Bugarska"},
            {"Venera", "Zemlja", "Mars", "Merkur"},
            {"Venecije", "Rima", "Milana", "Firence"},
            {"Talesova teorema", "Pitagorin zakon", "Fermaova teorema", "Kosinusna teorema"},
            {"Sisko u SAD", "Ispod La Manša", "Seikan u Japanu", "Između Švedske i Danske"},
            {"Bruce Willis", "Arnold Schwarzenegger", "Clint Eastwood", "Sylvester Stallone"},
            {"Tri", "Pet", "Četiri", "Šest"},
            {"Štraus", "Bah", "Mocart", "Betoven"},
            {"Dorate", "Alate", "Bele", "Vrane"},
            {"Bokser", "Rvač", "Karatista", "Džudista"},
            {"Petar Strugar", "Viktor Savić", "Nikola Kojo", "Sergej Trifunović"},
            {"10", "13", "11", "12"},
            {"Major", "Kapetan", "Pukovnik", "General-major"},
            {"1991.", "1993.", "1976", "2007."},
            {"Ogi", "Lora", "Tweety", "Ora"},
            {"1993.", "1996.", "1998.", "1999."},
            {"Al Fatah", "Crveni fes", "Crveni polumesec", "Zeleni krst"},
            {"101m", "73m", "152m", "203m"},
            {"ZIP", "YKK", "YPP", "ZKK"},
            {"Astronom", "Biolog", "Inženjer", "Industrijalac"},
            {"Bubanj i bas gitara", "Solo i ritam gitara", "Ritam i bas gitara", "Flauta i bubanj"},
            {"Biohemija", "Patologija", "Eritologija", "Hematologija"},
            {"Crkvi u Rimu", "Crkvi u Napulju", "Crkvi u Veneciji", "Crkvi u Milanu"},
            {"Karoline", "Ilinoisa", "Alabame", "Nevade"},
            {"U Bugarskoj", "U Moldaviji", "Na Kritu", "U Rumuniji"},
            {"1985. godine", "1980. godine", "1995. godine", "2008. godine"},
            {"Hrizantema", "Orhideja", "Trešnjin cvet", "Ljubičica"},
            {"U Egiptu", "U Maroku", "U Španiji", "U Francuskoj"},
            {"Microsofta", "McDonald'sa", "Electronic Artsa", "Hamonda"},
            {"Saobraćajne nezgode", "Trovanja morfijumom", "Avionske nezgode", "Strujnog udara"},
            {"1896. godine", "1901. godine", "1906. godine", "1893. godine"},
            {"Edinburg", "Glazgov", "Kardif", "London"},
            {"Sunca", "Podzemnog sveta", "Proleća", "Vina"},
            {"Miroslav Đukić", "Ratomir Đurković", "Javier Clemente", "Ilija Petković"},
            {"Emir Kusturica", "Želimir Žilnik", "Goran Paskaljević", "Goran Marković"},
            {"Gvožđe", "Dijamant", "Kobalt", "Uranijum"},
            {"Miligram", "Tropico band", "OK band", "Amadeus band"},
            {"Viski", "Vinjak", "Rakija", "Vodka"},
            {"Luksemburg", "Belgija", "Belorusija", "Holandija"},
            {"Triceratops", "Archeopteryx", "Brountosaurus", "Tirex"},
            {"Sliku", "Prezentaciju", "Tabelu", "Tekst dokument"},
            {"Ptičiji", "Svinjski", "Konjski", "Španski"},
            {"Rusije", "Poljske", "Ukrajine", "Belorusije"},
            {"Jednorog", "Grifon", "Minotaur", "Eaglion"},
            {"Justinijan", "Heraklije", "Konstantin VII", "Teodosije"},
            {"Zvezda padalica", "Galaksija", "Sazvežđe", "Reka"},
            {"Holandija", "Italija", "Francuska", "Hrvatska"},
            {"Finska", "Danska", "Švedska", "Francuska"},
            {"Odbojku", "Rukomet", "Plivanje", "Fudbal"},
            {"Mark Fiedel", "Cris Columb", "John McEaron", "Ben Johnson"},
            {"Od Federera", "Od Agassija", "Od Hewitta", "Od Raftera"},
            {"Trubama", "Lošem vremenu", "Svojim četama", "Konjima"},
            {"89+89/3+(89/3)/5", "Nema riba", "Sve su žive", "Mnogo"},
            {"e", "0", "2.71", "1"},
            {"Trg u Rimu", "Vrsta vina", "Arheološko nalazište u Srbiji", "Vatikanski spis"},
            {"999", "636", "969", "666"},
            {"Luksemburg", "Vatikan", "San Marino", "Monako"},
            {"Midžor", "Crni vrh", "Pančićev vrh", "Đeravica"},
            {"Kaligrafija", "Kriptografija", "Trafografija", "Grafoskopija"},
            {"U Jadranskom moru", "U Egejskom moru", "U Jonskom moru", "U Tirenskom moru"},
            {"Manastir Sopoćani", "Manastir Žiča", "Pećka patrijaršija", "Manastir Studenica"},
            {"Borussia Dortmund", "Real Madrid", "Porto", "Barcelona"},
            {"Robert Altman", "Robert Ladlam", "Robert Mitchum", "David Morrell"},
            {"Egipat", "Turska", "Mongolija", "Rusija"},
            {"Steven Spilberg", "James Cameron", "Tim Burton", "Luc Besson"},
            {"Za biologiju", "Za medicinu", "Za fiziku", "Za hemiju"},
            {"1969.", "1804.", "1937.", "1914."},
            {"Egiptom", "Grčkom", "Persijom", "Mesopotamijom"},
            {"Kardinal", "Nadbiskup", "Papa", "Pop"},
            {"Crnom Gorom", "Makedonijom", "Hrvatskom", "AP Kosovom i Metohijom"},
            {"Stefan Dečanski", "Dušan Silni", "Lazar Hrebeljanović", "Despot Stefan Lazarević"},
            {"Gosselin Leah", "Marizza De Capro", "Ana Maria Gepro", "Angelina Germanotta"},
            {"Morfologija", "Izometrologija", "Oblikologija", "Konturologija"},
            {"Zevs", "Herkul", "Sam se oslobodio", "Persefona"},
            {"Paprika", "Meso", "Kupus", "Mleko"},
            {"Odsutnost", "Nadležnost", "Podeljenost", "Zastarelost"},
            {"Will Smith", "Sean Penn", "Eddie Murphy", "Bruce Willis"},
            {"U Barseloni", "U Rimu", "U Londonu", "U Istambulu"},
            {"Afrika", "Amerika", "Okeanija", "Azija"},
            {"Walter Huston", "Cary Grant", "Kevin Spacey", "Louis Gossett Junior"},
            {"5", "2", "4", "3"},
            {"Hilandar", "Moskovska patrijaršija", "Dečani", "Aja Sofija"},
            {"U Ljubljani", "U Zagrebu", "U Šapcu", "U Beogradu"},
            {"Disciplina kičme", "EKV", "Električni orgazam", "Babe"},
            {"U Boki Kotorskoj", "U Gvinejskom", "U Kvarnerskom", "U Baskijskom"},
            {"Religijska knjiga", "Manjinski pokret", "Nepisani zakon", "Običajno pravo"},
            {"Engleska sobarica", "Zgrada u Dubajiju", "Vrsta papagaja", "Lekovita biljka"},
            {"Fomula I", "Košarke", "Fudbala", "Ratovanja"},
            {"Zloglasni zatvor u SAD", "Vrsta pauka", "Romanizovano keltsko ime za Beograd", "Grčki stari naziv za Beograd"},
            {"Ruski fudbaler", "Ruski kompozitor", "Ruski fizičar", "Američki kompozitor"},
            {"Crvena, plava i žuta", "Crna i bela", "Crvena, plava i zelena", "Ljubičasta, narandžasta i zelena"},
            {"Ravan", "Udubljen", "Ispupčen", "Ništa od navedenog"},
            {"Leb i sol", "Crvena jabuka", "Film", "Prljavo kazalište"},
            {"Zarazna bolest", "Zemljana posuda", "Bolest zuba", "Duboka, suva nizija"},
            {"Južne Koreje", "Kine", "Severne Koreje", "Japana"},
            {"U Urugvaju", "U Brazilu", "U Južnoj Africi", "U Rusiji"},
            {"Barselonu", "Real Madrid", "Atletiko Madrid", "Valensiju"},
            {"Austrije", "Izraela", "Ukrajine", "Kipra"},
            {"1930. godine", "1934. godine", "1942. godine", "1938. godine"},
            {"Jedno", "Dvoje", "Troje", "Četvoro"},
            {"1971. godine", "1987. godine", "1980. godine", "1985. godine"},
            {"Dvoje", "Nema dece", "Jedno", "Troje"},
            {"Bugarska", "Srbija", "Rumunija", "Holandija"},
            {"La Lakers", "Boston Celtics", "Sacramento Kings", "Cleveland Cavaliers"},
            {"U Kairu", "U Šangaju", "U Pekingu", "U Moskvi"},
            {"Punomoćje", "Dodatak", "Pozajmica", "Ugovor"},
            {"1810.", "1811.", "1813.", "1809."},
            {"Moamer Kasumović", "Senad Bašić", "Mustafa Nadarević", "Emir Hadžihafizbegović"},
            {"Sveti Stefan", "Sveti Grgur", "Sveti Martin", "Sveta Jelena"},
            {"Košuta", "Lane", "Srna", "Jelen"},
            {"Donald Trump", "Barack Obama", "Hillary Clinton", "Marco Rubio"},
            {"Tukidid", "Herodot", "Amijan Parcelin", "Eunapije iz Sarda"},
            {"13", "15", "17", "12"},
            {"Vatopedu", "Hilandaru", "Velikoj Lavri", "Sv. Panteleimonu"},
            {"Google", "Winamp", "Windows XP", "Facebook"},
            {"Sasa", "Kukurek", "Nana", "Paprat"},
            {"Kompjuterski virus", "Kompjuterski program", "Kompjuterski antivirus", "Operativni sistem"},
            {"Dance Jockey", "Disk Jockey", "Dance Jukebox", "Disk Jukebox"},
            {"Hondurasom i Kostarikom", "Tanzanijom, Ugandom, Sudanom, Etiopijom i Somalijom", "Tajlandom, Laosom i Vijetnamom", "Peruom, Bolivijom i Argentinom"},
            {"Dizzy Gillespie", "Miles Davis", "Louis Armstrong", "John Coltrane"},
            {"Azija", "Južna Amerika", "Afrika", "Severna Amerika"},
            {"Benjamin Disrael", "Mark Twain", "Geogre Orwell", "Charles Dickens"},
            {"Los Angeles Galaxy", "Manchester United", "Real Madrid", "Paris Saint-Germain"},
            {"Nilski konji", "Žirafe", "Veverice", "Zebre"},
            {"Kina", "Indija", "Egipat", "Portugalija"},
            {"Slon", "Plavi kit", "Žirafa", "Zelena anakonda"},
            {"Managua", "Medellin", "Bogota", "Tijuana"},
            {"Mjanmar", "Šri Lanka", "Laos", "Bangladeš"},
            {"Cassius Marcellus Clay, Jr", "Kareem Abdul-Jabbar", "Bobby Johnson", "Carl Weathers"},
            {"Tajland", "Vijetnam", "Peru", "Kambodža"},
            {"The Who", "Oasis", "The Police", "The Clash"},
            {"Inka", "Maja", "Asteka", "Tolteka"},
            {"U Atlanskom okeanu", "U  Indijskom okeanu", "U severnom ledenom okeanu", "U Tihom okeanu"},
            {"Uskog prostora", "Visine", "Zmija", "Paukova"},
            {"Casino Royale", "Live and let die", "Diamonds are forever", "From Russia with love"},
            {"U Madridu", "U Rimu", "U Barseloni", "U Veneciji"},
            {"Aleksandar Karađorđević", "Aleksandar Obrenović", "Milan Obrenović", "Mihailo Obrenović"},
            {"Ivan Rakitić", "Lionel Messi", "Cristiano Ronaldo", "Luka Modrić"},
            {"U Tanzaniji", "U Keniji", "U Etiopiji", "U Somaliji"},
            {"Kroz Moskvu", "Kroz Sankt Petersburg", "Kroz Kalinjingrad", "Kroz Kazanj"},
            {"Charles Dickens", "Erich Maria Remark", "Jules Verne", "Ernest Hemingway"},
            {"U Pruskoj", "U Austriji", "U Nemačkoj", "U Italiji"},
            {"Stranaca", "Visine", "Dubine", "Otvorenog prostora"},
            {"Islamabad", "Katmandu", "Pešavar", "Lasa"},
            {"Iz holandskog", "Iz belgijskog", "Iz novrveškog", "Iz češkog"},
            {"Lexington band", "Tropico band", "Dženan Lončarević", "Željko Joksimović"},
            {"Huawei P20", "Huawei P20 Lite", "Huawei P20 Pro", "Huawei P20 Mate"},
            {"Dubravka Mijatović", "Sloboda Mićalović", "Jelena Gavrilović", "Nada Šargin"},
            {"Toplo", "Sirovo", "Kuvano", "Hladno"},
            {"Kine", "Brazila", "Argentine", "Portugala"},
            {"Simbol velikog neprijatelja", "Šareni vez na donjem rubu damske haljine u 19. veku", "Prsluk koji mlada nosi prve bračne noći", "Cvet feniksa - simbol dana primirja u Prvom svetskom ratu"},
            {"Dragoslav Srejović", "Milorad M. Vasić", "Willard Libby", "John Aubrey"},
            {"1815.", "1878.", "1914.", "1943."},
            {"Medicini", "Slikarstvu", "Pisanju", "Muzici"},
            {"Crnomorskom", "Egejskom", "Severnomorkom", "Jadranskom"},
            {"Rakiću", "Iliću", "Antiću", "Radičeviću"},
            {"Vladislav Petković Dis", "Branislav Nušić", "Laza Lazarević", "Ivo Andrić"},
            {"Lee Harvey Oswalda", "Johna Lennona", "Marka Davida Chapmana", "Johna Kennedya"},
            {"Italija", "Engleska", "Kina", "Ujedinjeni Arapski Emirati"},
            {"1924.", "1923.", "1925.", "1930."},
            {"1930.", "1934.", "1935.", "1940."},
            {"Dativ", "Lokativ", "Instrumental", "Akuzativ"},
            {"Švedska", "Finska", "Švajcarska", "Litvanija"},
            {"Rumunijom", "Bugarskom", "Mađarskom", "Hrvatskom"},
            {"Dvanaest", "Sedam", "Devet", "Osam"},
            {"Veverice", "Nilski konji", "Žirafe", "Zebre"},
            {"Berlin", "Brisel", "Luksemburg", "Pariz"},
            {"Grafički znakovi dobijeni spajanjem dva ili tri slova", "Ukrasne minijature na sakralnim objektima", "Oznake na turističkim mapama", "Delovi u liturgiji koji se ponavljaju"},
            {"2010.", "2011.", "2016.", "2017."},
            {"A", "AB", "0", "B"},
            {"Johan Štraus stariji", "Johan Štraus mlađi", "Johan Sebastian Bah", "Eugen J. Bah"},
            {"Rock Hudston", "Humphrey Bogart", "John Wayne", "Gregory Peck"},
            {"Joy Page", "Madeleine Lebeau", "Ilka Grüning", "Ingrid Bergman"},
            {"Smrtonosno oružje", "Pobesneli Maks", "Terminator", "Umri muški"},
            {"Vulkana", "Planina", "Gradova", "Luka"},
            {"Kreativni nered", "Pandorina kutija", "Priroda i društvo", "Enfant terrible"},
            {"Sila", "‚Energija", "Znanje", "Um"},
            {"Kuglice", "Štapića", "Grozda", "Spirale"},
            {"Kermit", "Ralf", "Gonzo", "Waldorf"},
            {"Mangup", "Željo moja", "Rock me baby", "Ja sam za ples"},
            {"Životinja", "Uglova", "Svemira", "Engleza"},
            {"Ilija Garašanin", "Stojan Čupić", "Bajo Pivljanin", "Jovan Jovanović"},
            {"1876.", "1918.", "1871.", "1817."},
            {"Torino", "Real Madrid", "Honvéd", "Kišpešt"},
            {"1198.", "1196.", "1197.", "1194."},
            {"Viski", "Tekila", "Pivo", "Rum"},
            {"Jezerima", "Rekama", "Pećinama", "Okeanima"},
            {"Havajski", "Portugalski", "Kubanski", "Španski"},
            {"Paraf", "Šarlo akrobata", "Bijelo Dugme", "Pankrti"},
            {"Predrag Danilović", "Aleksandar Đorđević", "Vlade Divac", "Žarko Paspalj"},
            {"Španiji", "Italiji" , "Meksiku", "Portugaliji"},
            {"Kiseonik", "Vodonik", "Azot", "Ugljenik"},
            {"Geometar", "Učitelj", "Lekar", "Sveštenik"},
            {"Rezultanta", "Zbirna sila", "Skalarna", "Vektorska"},
            {"18", "20", "19", "36"},
            {"Avganistan", "Ukrajinu", "Belgiju", "Rusiju"},
            {"Darko Pančev", "Rajko Mitić", "Generacija iz 1991. godine", "Dragan Stojković Piksi"},
            {"Vrsta drveta", "Sušena riba", "Vrsta cveća", "Reka koja presuši"},
            {"1950.", "1941.", "1942.", "1949."},
            {"1.000 stepeni", "55.000 stepeni", "20.000 stepeni", "10.000 stepeni"},
            {"Arena", "Hipodrom", "Aja Sofija", "Zlatni rog"},
            {"Kit ajkula", "Plavi kit", "Morski pas", "Amazonski grgeč"},
            {"Plave", "Žute", "Crvene", "Narandžaste"},
            {"Advokat", "Pravobranilac", "Ombudsman", "Poslanik"},
            {"Jagodnji", "Maljenu", "Povlenu", "Suvoboru"},
            {"4", "6", "5", "7"},
            {"49", "279", "72", "125"},
            {"Ibar", "Resava", "Vlasina", "Morava"},
            {"Converse", "Puma", "Umbro", "Nike"},
            {"Jedna lasta ne čini proleće", "Mi o vuku, a vuk na vrata", "Sve svoje nosim sa sobom", "Kad na vrbi rodi grožđe"},
            {"Mars", "Snickers", "Twix", "Kidy"},
            {"The bad seeds", "The sailors", "The stooges", "The wailers"},
            {"Zarathustra", "Friedrich Wilhelm Nietzsche", "Arthur Schopenhauer", "Khalil Gibran"},
            {"Novo učenje", "Logičko pravilo", "Nova reč", "Nova pojava"},
            {"Astronaut", "Glumac", "Predsednik SAD", "Muzičar"},
            {"Čačak", "Požega", "Užice", "Kosjerić"},
            {"Glumac", "Muzičar", "Književnik", "Reditelj"},
            {"Budizam", "Deizam", "Ateizam", "Pluralizam"},
            {"1941. godine", "1939. godine", "1940. godine", "1942. godine"},
            {"Pacifik", "Misisipi", "Atlantik", "Misuri"},
            {"Komorska ostrva", "Sejšelska ostrva", "Kurilska ostrva", "Maldivi"},
            {"Nazaret", "Vitlajem", "Golgota", "Jordan"},
            {"Tremor", "Drhtavica", "Atrofija", "Katapleksija"},
            {"Divlje jagode", "Osvajači", "Riblja čorba", "Babe"},
            {"016", "019", "017", "020"},
            {"Konvergentan", "Divergentan", "Aritmetički", "Iracionalan"},
            {"Džudou", "Karateu", "Boksu", "Rvanju"},
            {"U Sargaskom moru", "U La manšu", "Bajkalskom jezeru", "U koritu Volge"},
            {"1815. godine", "1812. godine", "1821. godine", "1818. godine"},
            {"Aleksandar Makedonski", "Archimedes", "Aristoteles", "Einstein"},
            {"Konstantin Micotakis", "Konstantinos Karamanlis", "Aristotelis Onassis", "David Rockefeller"},
            {"Ateista", "Musliman", "Budista", "Hindus"},
            {"Sacramento", "Chicago", "Las Vegas", "Springfield"},
            {"1812. godine", "1782. godine", "1839. godine", "1917. godine"},
            {"Vaga", "Bik", "Rak", "Vodolija"},
            {"Vrsta plesa", "Plemićka titula", "Zamak", "Vrsta kolača"},
            {"Martin", "Juanes", "Kardoso", "Eskobar"},
            {"12", "10", "4", "11"},
            {"Turske", "Kine", "Ruske imperije", "Mongolije"},
            {"Sorbonne", "Stanford", "Yale", "Columbia"},
            {"Sava Šumanović", "Uroš Predić", "Pablo Picasso", "Uroš Đurić"},
            {"Mađarske", "Češke", "Poljske", "Rumunske"},
            {"Music", "21", "Love", "19"},
            {"Giovanni", "Galliani", "Amati", "Mastroianni"},
            {"Iz Češke", "Iz Vizantije", "Iz Bugarske", "Iz Slovačke"},
            {"Pelé", "Ronaldo", "Zico", "Sócrates"},
            {"Potisak", "Napon", "Intercija", "Energija"},
            {"25 minuta", "78 sekundi", "65 sati", "87 dana"},
            {"WHO", "Milenijum", "UNHCR", "UNESCO"},
            {"Nenaseljena oblast", "Naseljena oblast", "Prostrana travnata površina", "Vasionsko telo"},
            {"Tifus", "Malariju", "Kugu", "Velike boginje"},
            {"On", "Ona", "Olja", "Magi"},
            {"1960. godine", "1948. godine", "1955. godine", "1963. godine"},
            {"Inter", "Milan", "Juventus", "Napoli"},
            {"U Bremenu", "U Leipzigu", "U Münichu", "U Braunau"},
            {"Liftova", "Povraćanja", "Prelaska ulice", "Sireva"},
            {"Patrick Wilding", "Wandercy Fitzy", "Doc Lester", "Salomen Kinsky"},
            {"1946.", "1948.", "1971.", "1915."},
            {"U Arizoni", "U Texasu", "U Californiji", "U Tennesseeu"},
            {"Vrsta pumpe", "Alkoholno piće", "Gusti voćni sok", "Kisela voda"},
            {"220 Volt", "220 Watt", "220 Amper", "220 Tesla"},
            {"Kragujevca", "Kruševca", "Majdanpeka", "Knjaževca"},
            {"Kotanges", "Arkus kosinus", "Tanges hiperbolični", "Arkus tangens"},
            {"Marinka Rokvića", "Predraga Živkovića Tozovca", "Miroslava Ilića", "Tome Zdravkovića"},
            {"Orgulje", "Harmoniku", "Klavir", "Trubu"},
            {"Predrag Stojaković", "Dirk Nowitzki", "Pau Gasol", "Андрей Кириленко"},
            {"1739.", "1833.", "1930.", "1947."},
            {"Slavica", "Nevinost bez zaštite", "Rudareva sreća", "Grešnica bez greha"},
            {"Sahrana", "Svadba", "Bolest", "Grad"},
            {"Minerva", "Vesta", "Justicija", "Prozerpina"},
            {"Danilo", "Dušan", "Dimitrije", "David"},
            {"Carl Gustav Jung", "Erich Fromm", "Friedrich Nietzsche", "Sigismund Freud"},
            {"Fotosinteza", "Osmoza", "Fitokineza", "Fitoliza"},
            {"Rodezija", "Dahomej", "Zair", "Gornja Volta"},
            {"Anica Dobra", "Audrey Hepburn", "Kate Beckett", "Milla Jovovich"},
            {"Planina blizu Ljubovije", "Koštuljičavo voće", "Nalazište kamenog uglja", "Srednjovekovni grad"},
            {"Vrbas", "Kolubara", "Velika Morava", "Drina"},
            {"Trava", "Riba", "Vrsta čamca", "Otrovna pečurka"},
            {"Pisac", "Slikar", "Pronalazač", "Političar"},
            {"Moskva", "Rim", "Atina", "Pariz"},
            {"1945. godine", "1941. godine", "1943. godine", "1985. godine"},
            {"Egejsko", "Jadransko", "Jonsko", "Tirensko"},
            {"U Kičevu", "U Štipu", "U Gostivaru", "U Skoplju"},
            {"35", "30", "33", "37"},
            {"Real Madrid", "Barcelona", "Juventus", "Manchester United"},
            {"Biće krvi", "Pokajanje", "Nema zemlje za strance", "Džuno"},
            {"Pitagora", "Anaksimen", "Parmenid", "Heraklit"},
            {"Orao", "Soko", "Jastreb", "Svraka"},
            {"Krčman", "Šićardžija", "Bakalin", "Sitničar"},
            {"Brazil", "Kanada", "Indonezija", "Venecuela"},
            {"Golub", "Lešinar", "Orao", "Paun"},
            {"Dva puta", "Nisu osvojili", "Četiri puta", "Jednom"},
            {"Dragoslav Mihajlović", "Vladimir Arsenijević", "Miroslav Josić-Višnjić", "Svetislav Basara"},
            {"Forrest Gump", "Uhvati me ako možeš", "Osmi putnik", "Šindlerova lista"},
            {"Valjeva", "Čačka", "Niša", "Leskovca"},
            {"Branislava Nušića", "Branka Ćopića", "Miloša Crnjanskog", "Antonija Isakovića"},
            {"Marjan Beneš", "Slobodan Kačar", "Tadija Kačar", "Dragomir Vujković"},
            {"Vivien Leigh", "Audrey Hepburn", "Doris Day", "Marilyn Monroe"},
            {"Pet", "Četiri", "Dva", "Nula"},
            {"Benjamin Franklin", "Nikola Tesla", "Michael Faraday", "Alessandro Volta"},
            {"Nikola Tesla", "Hans Christian Ørsted", "Mihailo Pupin", "Thomas Edison"},
            {"Paralelno", "Kružno", "Dijagonalno", "Polukružno"},
            {"Lipa", "Kesten", "Hrast", "Platan"},
            {"Antifat", "Jolaj", "Lucifer", "Apis"},
            {"261.1m","171.1m", "420.1m", "310.1m"},
            {"Herta Müller", "Orhan Pamuk", "Mo Yan", "Mario Vargas Llosa"},
            {"Disperzija", "Depresijacija", "Dividenda", "Duopol"},
            {"Medved", "Lisica", "Veverica", "Vuk"},
            {"0.1 km", "0.6 km", "1 km", "6 km"},
            {"Peter Green", "Michael Roberts", "Tim Roth", "Bruce Willis"},
            {"Slikar", "Baletan", "Pisac", "Kompozitor"},
            {"Jadranski vetar", "Vrh na Kopaoniku", "Reka u Mađarskoj", "Podzemni vodotok"},
            {"20", "19", "11", "18"},
            {"Svima jednako", "Profesionalni učinak", "Opšte dobro", "Kralju u čast"},
            {"Bosna i Hercegovina", "Sandžak", "Makedonija", "Kosovo i Metohija"},
            {"1850. godine", "1890. godine", "1880. godine", "1873. godine"},
            {"Iz Nemačke", "Iz Holandije", "Iz Danske", "Iz Švedske"},
            {"Pijanicu", "Kolač", "Alavost", "Čast"},
            {"Leonardo", "Donatelo", "Mikelanđelo", "Miron"}





    };
    private String mCorrectAnswers [] = {
            "Proučavanjem mačaka",
            "1918.godine",
            "Osoba koja smatra da viša duhovna sila (božanstvo) možda postoji, ali da se ne može utvrditi oblik i priroda te sile",
            "Bill Gates",
            "Tesla(T)",
            "Roterdam",
            "Adenin, citozin, guanin i uracil",
            "Jaki i kratkotrajni",
            "Kalaj",
            "Laza Kostić",
            "Predrag Živković Tozovac",
            "ROM",
            "Java Virtual Machine",
            "Geri Oldman",
            "Ludwig van Beethoven",
            "Ðorda Vajferta",
            "Mladalačko doba",
            "Dragan Nikolić",
            "Vojni savez",
            "42km",
            "FC Bayern München",
            "Nepovratni procesi",
            "Bolesti srca",
            "4",
            "Mira",
            "Srbija",
            "Lane moje",
            "1836.",
            "Sendvič",
            "Sebastian Fetel",
            "Izvršnu",
            "Sahara",
            "Salvador Dali",
            "Kolubarskog okruga",
            "Životnu sredinu",
            "Golmana",
            "8 minuta",
            "Vuk Kostić",
            "Pevač džeza",
            "Kompjuterskih igrica",
            "Rio de Žaneiru",
            "Portugalija",
            "Ubistvo iz milosrđa",
            "2,54cm",
            "Indonezija",
            "Led Zeppelin",
            "J.R.R.Tolkien",
            "1969.",
            "Vina",
            "Mick Jagger",
            "Cilindričnu građevinu",
            "Višebojnost",
            "Nikola Dobrović",
            "Podzemni prolazi ili prostorije",
            "Dudovim lišćem",
            "Smanjenje nataliteta",
            "Pandan",
            "Long play",
            "Novak Đoković",
            "Drugo mesto - srebro",
            "THCF",
            "2016.",
            "Bukefal",
            "Mislim, dakle postojim",
            "Istog saliniteta",
            "Kvačilo",
            "Miloš Teodosić",
            "U Valjevu",
            "Od 1322. do 1331. godine",
            "Milan Vasić",
            "Mihailo Obrenović",
            "Antonije Isaković",
            "VIII",
            "U Milanu",
            "Mali medved",
            "Braća",
            "Spasovdan",
            "50",
            "Vasilij Kandinski",
            "Sankt Peterburg",
            "Lexington band",
            "E",
            "Matematike",
            "Lovac",
            "Ljubičaste",
            "Nemačku",
            "0",
            "U Valjevu",
            "Vudstok",
            "Jednom",
            "U aprilu",
            "Na Kritu",
            "Jedanaest",
            "Engleski",
            "A",
            "Rihanna",
            "1945.",
            "U Amboazu",
            "Vrsta hominida",
            "U Velikoj Britaniji",
            "Kompjutera",
            "Metalni novac",
            "Grčka",
            "Venera",
            "Rima",
            "Kosinusna teorema",
            "Seikan u Japanu",
            "Bruce Willis",
            "Šest",
            "Štraus",
            "Vrane",
            "Rvač",
            "Petar Strugar",
            "12",
            "Major",
            "1991.",
            "Ogi",
            "1999.",
            "Crveni polumesec",
            "101m",
            "YKK",
            "Biolog",
            "Bubanj i bas gitara",
            "Hematologija",
            "Crkvi u Veneciji",
            "Ilinoisa",
            "Na Kritu",
            "2008. godine",
            "Hrizantema",
            "U Španiji",
            "Microsofta",
            "Trovanja morfijumom",
            "1893. godine",
            "London",
            "Podzemnog sveta",
            "Miroslav Đukić",
            "Goran Paskaljević",
            "Dijamant",
            "Miligram",
            "Vodka",
            "Belorusija",
            "Archeopteryx",
            "Tekst dokument",
            "Svinjski",
            "Rusije",
            "Grifon",
            "Teodosije",
            "Sazvežđe",
            "Holandija",
            "Danska",
            "Plivanje",
            "Ben Johnson",
            "Od Agassija",
            "Trubama",
            "Sve su žive",
            "1",
            "Arheološko nalazište u Srbiji",
            "999",
            "Vatikan",
            "Đeravica",
            "Kaligrafija",
            "U Egejskom moru",
            "Manastir Žiča",
            "Barcelona",
            "Robert Ladlam",
            "Mongolija",
            "James Cameron",
            "Za fiziku",
            "1937.",
            "Egiptom",
            "Papa",
            "AP Kosovom i Metohijom",
            "Dušan Silni",
            "Angelina Germanotta",
            "Morfologija",
            "Herkul",
            "Mleko",
            "Nadležnost",
            "Eddie Murphy",
            "U Londonu",
            "Azija",
            "Cary Grant",
            "3",
            "Aja Sofija",
            "U Šapcu",
            "Disciplina kičme",
            "U Gvinejskom",
            "Religijska knjiga",
            "Vrsta papagaja",
            "Fudbala",
            "Grčki stari naziv za Beograd",
            "Ruski kompozitor",
            "Crvena, plava i žuta",
            "Ispupčen",
            "Crvena jabuka",
            "Zarazna bolest",
            "Japana",
            "U Južnoj Africi",
            "Barselonu",
            "Izraela",
            "1930. godine",
            "Dvoje",
            "1980. godine",
            "Troje",
            "Bugarska" ,
            "Boston Celtics",
            "U Pekingu",
            "Punomoćje",
            "1811.",
            "Moamer Kasumović",
            "Sveta Jelena",
            "Košuta",
            "Donald Trump",
            "Herodot",
            "13",
            "Sv. Panteleimonu",
            "Winamp",
            "Sasa",
            "Kompjuterski antivirus",
            "Disk Jockey",
            "Hondurasom i Kostarikom",
            "Miles Davis",
            "Južna Amerika",
            "Geogre Orwell",
            "Paris Saint-Germain",
            "Veverice",
            "Kina",
            "Plavi kit",
            "Bogota",
            "Mjanmar",
            "Cassius Marcellus Clay, Jr",
            "Kambodža",
            "The Police",
            "Inka",
            "U Tihom okeanu",
            "Visine",
            "Casino Royale",
            "U Veneciji",
            "Milan Obrenović",
            "Luka Modrić",
            "U Tanzaniji",
            "Kroz Sankt Petersburg",
            "Ernest Hemingway",
            "U Austriji",
            "Stranaca",
            "Katmandu",
            "Iz holandskog",
            "Dženan Lončarević",
            "Huawei P20 Mate",
            "Sloboda Mićalović",
            "Hladno",
            "Brazila",
            "Cvet feniksa - simbol dana primirja u Prvom svetskom ratu",
            "Dragoslav Srejović",
            "1914.",
            "Slikarstvu",
            "Crnomorskom",
            "Radičeviću",
            "Laza Lazarević",
            "Lee Harvey Oswalda",
            "Kina",
            "1924.",
            "1934.",
            "Akuzativ",
            "Švajcarska",
            "Rumunijom",
            "Devet",
            "Veverice",
            "Brisel",
            "Grafički znakovi dobijeni spajanjem dva ili tri slova",
            "2016.",
            "0",
            "Johan Štraus stariji",
            "Humphrey Bogart",
            "Ingrid Bergman",
            "Pobesneli Maks",
            "Vulkana",
            "Priroda i društvo",
            "Um",
            "Štapića",
            "Kermit",
            "Ja sam za ples",
            "Engleza",
            "Stojan Čupić",
            "1871.",
            "Torino",
            "1197.",
            "Rum",
            "Rekama",
            "Španski",
            "Šarlo akrobata",
            "Aleksandar Đorđević",
            "Španiji",
            "Azot",
            "Učitelj",
            "Rezultanta",
            "19",
            "Rusiju",
            "Generacija iz 1991. godine",
            "Vrsta drveta",
            "1942.",
            "20.000 stepeni",
            "Hipodrom",
            "Kit ajkula",
            "Crvene",
            "Ombudsman",
            "Jagodnji",
            "6",
            "72",
            "Morava",
            "Puma",
            "Jedna lasta ne čini proleće",
            "Twix",
            "The bad seeds",
            "Friedrich Wilhelm Nietzsche",
            "Nova reč",
            "Muzičar",
            "Čačak",
            "Književnik",
            "Deizam",
            "1941. godine",
            "Misuri",
            "Kurilska ostrva",
            "Golgota",
            "Tremor",
            "Divlje jagode",
            "019",
            "Konvergentan",
            "Rvanju",
            "Bajkalskom jezeru",
            "1815. godine",
            "Archimedes",
            "Aristotelis Onassis",
            "Hindus",
            "Springfield",
            "1812. godine",
            "Bik",
            "Vrsta kolača",
            "Juanes",
            "12",
            "Ruske imperije",
            "Columbia",
            "Pablo Picasso",
            "Mađarske",
            "19",
            "Amati",
            "Iz Vizantije",
            "Pelé",
            "Energija",
            "78 sekundi",
            "UNESCO",
            "Nenaseljena oblast",
            "Kugu",
            "Ona",
            "1955. godine",
            "Napoli",
            "U Braunau",
            "Povraćanja",
            "Patrick Wilding",
            "1971.",
            "U Californiji",
            "Alkoholno piće",
            "220 Volt",
            "Knjaževca",
            "Kotanges",
            "Miroslava Ilića",
            "Harmoniku",
            "Андрей Кириленко",
            "1947.",
            "Nevinost bez zaštite",
            "Sahrana",
            "Prozerpina",
            "Dimitrije",
            "Sigismund Freud",
            "Osmoza",
            "Rodezija",
            "Milla Jovovich",
            "Planina blizu Ljubovije",
            "Velika Morava",
            "Riba",
            "Političar",
            "Rim",
            "1943. godine",
            "Jonsko",
            "U Kičevu",
            "33",
            "Real Madrid",
            "Nema zemlje za strance",
            "Heraklit",
            "Soko",
            "Bakalin",
            "Brazil",
            "Paun",
            "Jednom",
            "Vladimir Arsenijević",
            "Osmi putnik",
            "Niša",
            "Branislava Nušića",
            "Slobodan Kačar",
            "Marilyn Monroe",
            "Četiri",
            "Benjamin Franklin",
            "Hans Christian Ørsted",
            "Paralelno",
            "Hrast",
            "Apis",
            "261.1m",
            "Mo Yan",
            "Depresijacija",
            "Vuk",
            "0.1 km",
            "Michael Roberts",
            "Pisac",
            "Podzemni vodotok",
            "20",
            "Opšte dobro",
            "Bosna i Hercegovina",
            "1873. godine",
            "Iz Holandije",
            "Čast",
            "Mikelanđelo"
    };


    public String getmQuestions(int a) {
        String question = mQuestions[a];
        return question;
    }
    public String getChoice1 (int a) {
        String choice = mChoices[a][0];
        return choice;
    }
    public String getChoice2 (int a) {
        String choice = mChoices[a][1];
        return choice;
    }
    public String getChoice3 (int a) {
        String choice = mChoices[a][2];
        return choice;
    }
    public String getChoice4 (int a) {
        String choice = mChoices[a][3];
        return choice;
    }
    public String getCorrectAnswer(int a){
        String answer = mCorrectAnswers[a];
        return answer;
    }
}
