package andjelka.kvizpliz;

import android.content.Context;

import java.util.ArrayList;
import java.util.List;

public class Questions
{
    List<Question> list = new ArrayList<>();

    DbHelper dbHelper;

    //Metoda koja vraca velicinu liste tj broj pitanja u listi
    public int getLength()
    {
        return list.size();
    }

    //Metoda koja vraca pitanje iz liste
    public String getQuestion(int a)
    {
        return list.get(a).getQuestion();
    }

    //Moguci odgovori
    public String getChoice(int index, int num)
    {
        return list.get(index).getChoice(num-1);
    }

    //Tacan odgovor iz liste
    public String getCorrectAnswer(int a)
    {
        return list.get(a).getAnswer();
    }

    //Inicijalnizacija liste u slucaju da je prazna
    public void initQuests(Context context)
    {
        dbHelper = new DbHelper(context);

        list = dbHelper.getAllQuestions();

        if(list.isEmpty())
        {
            dbHelper.addInitQuestion(new Question("Čime se bavi felinolog?", new String[] {"Proučavanjem mačaka", "Proučavanjem pasa", "Proučavanjem perja", "Proučavanjem lekovitih biljaka"}, "Proučavanjem mačaka"));
            dbHelper.addInitQuestion(new Question("Kada je osnovana SHS?", new String[] {"1914. godine", "1915.godine", "1918.godine", "1945.godine"}, "1918.godine"));
            dbHelper.addInitQuestion(new Question("Ko je agnostik?", new String[] {"Nevernik", "Osoba koja pati od brojnih fobija", "Osoba koja nema pouzdanja u svoje znanje", "Osoba koja smatra da viša duhovna sila (božanstvo) možda postoji, ali da se ne može utvrditi oblik i priroda te sile"}, "Osoba koja smatra da viša duhovna sila (božanstvo) možda postoji, ali da se ne može utvrditi oblik i priroda te sile"));
            dbHelper.addInitQuestion(new Question("Ko je osnovao kompaniju Microsoft?", new String[] {"Steve Jobs", "Bill Gates", "Lawrence (Larry) Page", "Mark Zuckerberg"}, "Bill Gates"));
            dbHelper.addInitQuestion(new Question("U kojim jedinicama se izražava magnetna indukcija?", new String[] {"Tesla (T)", "Veber (Wb)", "Džul (J)", "Paskal (Pa)"}, "Tesla (T)"));
            dbHelper.addInitQuestion(new Question("Koja je najveća evropska luka po prometu?", new String[] {"Roterdam", "Antverpen", "Marsej", "Hamburg"}, "Roterdam"));
            dbHelper.addInitQuestion(new Question("U sastav RNK ulaze?", new String[] {"Adenin, timin, citozin i guanin", "Adenin, citozin, guanin i uracil", "Adenin, citozin, uracil i timin", "Adenin, timin, guanin i uracil"}, "Adenin, citozin, guanin i uracil"));
            dbHelper.addInitQuestion(new Question("Afekti su emocionalni doživljaji koji su:", new String[] {"Slabi i dugotrajni", "Jaki i dugotrajni", "Slabi i kratkotrajni", "Jaki i kratkotrajni"}, "Jaki i kratkotrajni"));
            dbHelper.addInitQuestion(new Question("Sn je hemijski simbol?", new String[] {"Antimon", "Stroncijum", "Kalaj", "Srebro"}, "Kalaj"));
            dbHelper.addInitQuestion(new Question("Ko je autor pesme 'Santa Maria della Salute'?", new  String[] {"Laza Kostić", "Aleksa Šantić", "Milan Rakić", "Dušan Vasiljev"}, "Laza Kostić"));
            dbHelper.addInitQuestion(new Question("Ko peva pesmu 'Oči jedne žene'?", new String[]{"Miroslav Ilić", "Predrag Živković Tozovac", "Haris Džinović", "Šaban Šaulić"}, "Predrag Živković Tozovac"));
            dbHelper.addInitQuestion(new Question("Statički deo memorije, koji može samo da se čita, označava se kao:", new String[] {"RAM", "ROM", "Keš", "Buffer"}, "ROM"));
            dbHelper.addInitQuestion(new Question("Šta je JVM?", new String[] {"Java Visual Method", "Java Virtual Machine", "Java Visual Machine", "Java Virtual Method"}, "Java Virtual Machine"));
            dbHelper.addInitQuestion(new Question("Ko tumači lik Harijevog kuma u filmu 'Harry Potter'?", new String[] {"Geri Oldman", "David Thewlis", "Robbie Coltrane", "Alan Rickman"}, "Geri Oldman"));
            dbHelper.addInitQuestion(new Question("Ko je komponovao 'Odu radosti'?", new String[] {"Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Felix Mendelssohn", "Hector Berlioz"}, "Ludwig van Beethoven"));
            dbHelper.addInitQuestion(new Question("Čiji lik se nalazi na novčanici od 1000 dinara?", new String[] {"Vuka Stefanovića Karadžića", "Ðorda Vajferta", "Nikole Tesle", "Jovana Cvijića"}, "Ðorda Vajferta"));
            dbHelper.addInitQuestion(new Question("Adolescencija je:", new String[] {"Detinjstvo", "Zrelo doba", "Mladalačko doba", "Staračko doba"}, "Mladalačko doba"));
            dbHelper.addInitQuestion(new Question("Koji glumac nije igrao u filmu Maratonci trce pocasni krug?", new String[] {"Bogdan Diklić", "Bora Todorović", "Dragan Nikolić", "Zoran Radmilović"}, "Dragan Nikolić"));
            dbHelper.addInitQuestion(new Question("NATO savez je:", new String[] {"Ekonomski savez", "Kulturni savez", "Vojni savez", "Politički savez"}, "Vojni savez"));
            dbHelper.addInitQuestion(new Question("Koliko iznosi dužina staze za maratonsku trku?", new String[]{"42km", "35km", "22km", "32km"}, "42km"));
            dbHelper.addInitQuestion(new Question("Za koji fudbalski klub igra poljski fudbaler Robert Lewandowski (Sezona 2022/23)?", new String[] {"FC Barcelona", "Borussia Dortmund", "FC Bayern München", "KKS Lech Poznan"}, "FC Barcelona"));
            dbHelper.addInitQuestion(new Question("Kakvi su ireverzibilni procesi?", new String[] {"Procesi koji se mogu kontrolisati", "Nepromenljivi procesi", "Kratkotrajni procesi", "Nepovratni procesi"}, "Nepovratni procesi"));
            dbHelper.addInitQuestion(new Question("Šta leči kardiolog?", new String[] {"Bolesti srca", "Bolesti jetre", "Nasledne bolesti", "Bolesti pluća"}, "Bolesti srca"));
            dbHelper.addInitQuestion(new Question("Koji broj na dresu nosi Miloš Teodosić?", new String[] {"9", "4", "11", "5"}, "4"));
            dbHelper.addInitQuestion(new Question("Maslinova grančica je simbol:", new String[] {"Mira", "Slobode", "Hrabrosti", "Pravde"}, "Mira"));
            dbHelper.addInitQuestion(new Question("Ko je osvojio Davis cup 2010. godine?", new String[] {"Francuska", "Češka", "Srbija", "Velika Britanija"}, "Srbija"));
            dbHelper.addInitQuestion(new Question("Na Eurosongu 2004. godine Srbiju je predstavljao Željko Joksimovic sa pesmom:", new String[] {"Nije ljubav stvar", "Lane moje", "Supermen", "Balada"}, "Lane moje"));
            dbHelper.addInitQuestion(new Question("Koje godine je slovo H uvedeno u srpski jezik?", new String[] {"1834.", "1835.", "1836.", "1838."}, "1836."));
            dbHelper.addInitQuestion(new Question("Na poljskom kanapka, a na srpskom:", new String[] {"Sendvič", "Čokolada", "Večera", "Posteljina"}, "Sendvič"));
            dbHelper.addInitQuestion(new Question("Najmlađi šampion u formuli 1 je:", new String[] {"Michael Schumacher", "Lewis Hamilton", "Sebastian Fetel", "Nico Rosberg"}, "Sebastian Fetel"));
            dbHelper.addInitQuestion(new Question("Kakvu vlast ima vlada Republike Srbije?", new String[] {"Sudsku", "Izvršnu", "Zakonodavnu", "Vrhovnu"}, "Izvršnu"));
            dbHelper.addInitQuestion(new Question("Najveca pustinja na Zemlji je:", new String[] {"Gobi", "Sahara", "Kalahari", "Velika pešcana pustinja"}, "Sahara"));
            dbHelper.addInitQuestion(new Question("Koji slikar je kreirao logo za Chupa Chups?", new String[] {"Pablo Picasso", "Leonardo da Vinci", "Salvador Dali", "Francisco Goya"}, "Salvador Dali"));
            dbHelper.addInitQuestion(new Question("Grad Valjevo je sedište:", new String[] {"Pčinjskog okruga", "Mačvanskog okruga", "Kolubarskog okruga", "Zlatiborskog okruga"}, "Kolubarskog okruga"));
            dbHelper.addInitQuestion(new Question("Šta proučava ekologija?", new String[] {"Životnu sredinu", "Insekte", "Poreklo reči", "Vina"}, "Životnu sredinu"));
            dbHelper.addInitQuestion(new Question("Legendarni nemački fudbaler Oliver Kahn igrao je na poziciji:", new String[] {"Veznog igrača", "Napadača", "Golmana", "Odbrambenog igrača"}, "Golmana"));
            dbHelper.addInitQuestion(new Question("Koliko traje jedna četvrtina u vaterpolo utakmici?", new String[] {"10 minuta", "7 minuta", "8 minuta", "5 minuta"}, "8 minuta"));
            dbHelper.addInitQuestion(new Question("U seriji Ubice mog oca, lik inspektora iz Odeljenja za krvne delikte tumači:", new String[] {"Vuk Kostić", "Marko Janketić", "Tihomir Stanić", "Slavko Štimac"}, "Vuk Kostić"));
            dbHelper.addInitQuestion(new Question("Prvi zvučni film je:", new String[] {"Veliki diktator", "Pevač džeza", "Nevinost bez zaštite", "Svetla New Yorka"}, "Pevač džeza"));
            dbHelper.addInitQuestion(new Question("Nordeus je kompanija koja se bavi pravljenjem:", new String[] {"Video igrica", "Antivirus programa", "Računarske opreme", "Programa za obradu fotografija"}, "Video igrica"));
            dbHelper.addInitQuestion(new Question("Olimpijske igre 2016. godine održane su u:", new String[] {"Londonu", "Pekingu", "Tokiju", "Rio de Žaneiru"}, "Rio de Žaneiru"));
            dbHelper.addInitQuestion(new Question("Koja zemlja je pobednik Eurosonga 2017. godine?", new String[] {"Portugalija", "Australija", "Ukrajina", "Izrael"}, "Portugalija"));
            dbHelper.addInitQuestion(new Question("Eutanazija je:", new String[] {"Ubistvo iz nehata", "Ubistvo iz milosrđa", "Ubistvo iz koristoljublja", "Ubistvo iz osvete"}, "Ubistvo iz milosrđa"));
            dbHelper.addInitQuestion(new Question("Koliko iznosi jedan inch?", new String[] {"1,54 cm", "2,44 cm", "2,54 cm", "2,64 cm"}, "2,54 cm"));
            dbHelper.addInitQuestion(new Question("U kojoj državi se nalazi najviše vulkana?", new String[] {"U Japanu", "U Indoneziji", "U Meksiku", "U Italiji"}, "U Indoneziji"));
            dbHelper.addInitQuestion(new Question("Koji bend je osnovao Jimmy Page?", new String[] {"Led Zeppelin", "Queen", "Pink Floyd", "The Beatles"}, "Led Zeppelin"));
            dbHelper.addInitQuestion(new Question("Ko je napisao delo 'Gospodar prstenova'?", new String[] {"Suzanne Collins", "J.R.R.Tolkien", "J.K.Rowling", "George R.R.Martin"}, "J.R.R.Tolkien"));
            dbHelper.addInitQuestion(new Question("Koje godine je Neil Armstrong sleteo na Mesec?", new String[] {"1959.", "1965.", "1969.", "1962."}, "1969."));
            dbHelper.addInitQuestion(new Question("Enolog je poznavalac:", new String[] {"Rakije", "Piva", "Viskija", "Vina"}, "Vina"));
            dbHelper.addInitQuestion(new Question("Kako se zove frontmen grupe The Rolling Stones?", new String[] {"Mick Jagger", "Michael Jordan", "Michael Jackson", "Jerry Lewis"}, "Mick Jagger"));
            dbHelper.addInitQuestion(new Question("Rotonda označava:", new String[] {"Silos", "Mlin", "Crkvu", "Cilindričnu građevinu"}, "Cilindričnu građevinu"));
            dbHelper.addInitQuestion(new Question("Šta je polihronija?", new String[] {"Višeboj", "Višebojnost", "Grčka proročica", "Privremeno slepilo"}, "Višebojnost"));
            dbHelper.addInitQuestion(new Question("Koji arhitekta je stvorio urbanističku koncepciju Novog Beograda?", new String[] {"Milan Zloković", "Jan Nevole", "Nikola Dobrović", "Aleksej Brkić"}, "Nikola Dobrović"));
            dbHelper.addInitQuestion(new Question("Šta su lagumi?", new String[] {"Podzemni prolazi ili prostorije", "Poluzatvoreni nadzemni prostori", "Zatvoreni prostori na osojnim padinama", "Prostorije na prirodno osunčanim prisojnim padinama"}, "Podzemni prolazi ili prostorije"));
            dbHelper.addInitQuestion(new Question("Čime se hrani svilena buba?", new String[] {"Dudovim lišćem", "Smolom", "Lišajevima", "Larvama mrava"}, "Dudovim lišćem"));
            dbHelper.addInitQuestion(new Question("Šta je 'bela kuga'?", new String[] {"Smanjenje nataliteta", "Smanjenje mortaliteta", "Porast nataliteta", "Porast mortaliteta"}, "Smanjenje nataliteta"));
            dbHelper.addInitQuestion(new Question("Eros i Amor su jedan drugome:", new String[] {"Osiromašenje građana", "Unikat", "Pandan", "Sinonimi"}, "Pandan"));
            dbHelper.addInitQuestion(new Question("Koja vrsta gramofonskih ploča se vrti na 33 obrtaja?", new String[] {"Ne postoji takva vrsta ploča", "Singl", "Extended play", "Long play"}, "Long play"));
            dbHelper.addInitQuestion(new Question("Prvi avion kompanije 'Air Serbia' nosi naziv:", new String[] {"Novak Đoković", "Vlade Divac", "Nikola Tesla", "Miki Manojlović"}, "Novak Đoković"));
            dbHelper.addInitQuestion(new Question("Koje mesto je zauzela muška košarkaška reprezentacija Srbije na Olimpijskim igrama 2016. godine?", new String[] {"Četvrto mesto", "Drugo mesto - srebro", "Treće mesto - bronza", "Prvo mesto - zlato"}, "Drugo mesto - srebro"));
            dbHelper.addInitQuestion(new Question("Pesmu 'Igraj i pobedi' izvodi grupa:", new String[] {"Goša sa raskršća", "Beogradski sindikat", "THCF", "Neguj mo Srbski"}, "THCF"));
            dbHelper.addInitQuestion(new Question("Koje godine je izašao prvi iPhone SE?", new String[] {"2016.", "2015.", "2017.", "2020."}, "2016."));
            dbHelper.addInitQuestion(new Question("Kako se zvao konj Aleksandra Velikog?", new String[] {"Lamri", "Arnaut", "Rosinanta", "Bukefal"}, "Bukefal"));
            dbHelper.addInitQuestion(new Question("Cogito, ergo sum ili?", new String[] {"Kocka je bačena", "Mislim, dakle postojim", "Dođoh, videh, pobedih", "U vinu je istina"}, "Mislim, dakle postojim"));
            dbHelper.addInitQuestion(new Question("Izohaline su tačke koje spajaju mesta:", new String[] {"Iste nadmorske visine", "Istog pritiska", "Iste gustine vazduha, stena...", "Istog saliniteta"}, "Istog saliniteta"));
            dbHelper.addInitQuestion(new Question("Na nemačkom Kuplung, a na srpskom?", new String[] {"Gas", "Kvačilo", "Brzina", "Kočnica"}, "Kvačilo"));
            dbHelper.addInitQuestion(new Question("Ko je bio kapiten muške seniorske reprezentacije na OI 2016. godine?", new String[] {"Miloš Teodosić", "Milan Mačvan", "Nenad Krstić", "Stefan Marković"}, "Miloš Teodosić"));
            dbHelper.addInitQuestion(new Question("U kom gradu je rođen fudbaler Matija Nastasić?", new String[] {"U Obrenovcu", "U Beogradu", "U Valjevu", "U Šapcu"}, "U Valjevu"));
            dbHelper.addInitQuestion(new Question("Stefan Uroš III Dečanski vladao je Srbijom:", new String[] {"Od 1282. do 1321. godine", "Od 1322. do 1331. godine", "Od 1331. do 1355. godine", "Od 1355. do 1371. godine"}, "Od 1322. do 1331. godine"));
            dbHelper.addInitQuestion(new Question("Ko igra glavnu mušku ulogu u filmu 'Vrati se Zone'?", new String[] {"Milan Vasić", "Vojin Ćetković", "Milan Lane Gutović", "Nikola Ristanovski"}, "Milan Vasić"));
            dbHelper.addInitQuestion(new Question("Koji srpski vladar je ubijen na Košutnjaku?", new String[] {"Milan Obrenović", "Miloš Obrenović", "Aleksandar Obrenović", "Mihailo Obrenović"}, "Mihailo Obrenović"));
            dbHelper.addInitQuestion(new Question("Ko je napisao pripovetku 'Kašika'?", new String[] {"Simo Matavulj", "Antonije Isaković", "Laza Lazarević", "Milovan Glišić"}, "Antonije Isaković"));
            dbHelper.addInitQuestion(new Question("Kojoj FCI grupi pripada rasa pasa Labrador?", new String[] {"VII", "VIII", "X", "IX"}, "VIII"));
            dbHelper.addInitQuestion(new Question("U kom gradu u Italiji se nalazi katedrala Duomo?", new String[] {"U Rimu", "U Firenci", "U Veneciji", "U Milanu"}, "U Milanu"));
            dbHelper.addInitQuestion(new Question("U kom sazvežđu se nalazi zvezda Severnjača?", new String[] {"Mali medved", "Veliki medved", "Mala kola", "Veliki pas"}, "Mali medved"));
            dbHelper.addInitQuestion(new Question("U kakvim su rodbinskim odnosima osnivači kompanija Puma i Adidas su?", new String[] {"Otac i sin", "Deda i unuk", "Nisu u srodstvu", "Braća"}, "Braća"));
            dbHelper.addInitQuestion(new Question("Slava grada Beograda je?", new String[] {"Trojice", "Sveta Petka", "Spasovdan", "Krstovdan"}, "Spasovdan"));
            dbHelper.addInitQuestion(new Question("Koliko dana posle Vaskrsa se obeležavaju Duhovi ili Trojice?", new String[] {"30", "50", "10", "40"}, "50"));
            dbHelper.addInitQuestion(new Question("Plavog jahača je naslikao?", new String[] {"Vasilij Kandinski", "Lovis Corinth", "Aleksej von Jawlensky", "August Macke"}, "Vasilij Kandinski"));
            dbHelper.addInitQuestion(new Question("Nekada Lenjingrad, a danas?", new String[] {"Volgograd", "Sankt Peterburg", "Novgorod", "Belgorod"}, "Sankt Peterburg"));
            dbHelper.addInitQuestion(new Question("Pesmu 'Na dlanu' izvodi?", new String[] {"OK band", "Tropico band", "Lapsus band", "Lexington band"}, "Lexington band"));
            dbHelper.addInitQuestion(new Question("Koji vitamin se nalazi u bademu?", new String[] {"A", "D", "E", "B"}, "E"));
            dbHelper.addInitQuestion(new Question("'Kengur bez granica' je međunarodno takmičenje iz oblasti?", new String[] {"Matematike", "Fizike", "Hemije", "Informatike"}, "Matematike"));
            dbHelper.addInitQuestion(new Question("Laufer ili?", new String[] {"Top", "Lovac", "Skakač", "Pešak"}, "Lovac"));
            dbHelper.addInitQuestion(new Question("Koje boje je dragi kamen ametist?", new String[] {"Tirkizne", "Ružičasto-crvene", "Plave", "Ljubičaste"}, "Ljubičaste"));
            dbHelper.addInitQuestion(new Question("+49 je pozivni broj za:", new String[] {"Francusku", "Nemačku", "Italiju", "Veliku Britaniju"}, "Nemačku"));
            dbHelper.addInitQuestion(new Question("Koliko 1 bit ima bajta?", new String[] {"8", "1", "0", "12"}, "0"));
            dbHelper.addInitQuestion(new Question("U kom gradu se nalazi spomenik Stevanu Filipoviću?", new String[] {"U Valjevu", "U Opuzenu", "U Mostaru", "U Kragujevcu"}, "U Valjevu"));
            dbHelper.addInitQuestion(new Question("Kako se zove verni pratilac Snupija?", new String[] {"Kalimero", "Tweety", "Gonzales", "Vudstok"}, "Vudstok"));
            dbHelper.addInitQuestion(new Question("Koliko puta je ženska rukometna reprezentacije Jugoslavije bila prvak sveta?", new String[] {"Tri puta", "Nijednom", "Jednom", "Četiri puta"}, "Jednom"));
            dbHelper.addInitQuestion(new Question("U kom mesecu se obeležava svetski dan knjige?", new String[] {"U julu", "U aprilu", "U oktobru", "U decembru"}, "U aprilu"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi grad Retimno?", new String[] {"U Bugarskoj", "Na Kritu", "Na Kipru", "U Rumuniji"}, "Na Kritu"));
            dbHelper.addInitQuestion(new Question("Osoba X stane u red i spreda je peti, a otpozadi sedmi. Koliko ima ljudi u redu?", new String[] {"Četrnaest", "Dvanaest", "Trinaest", "Jedanaest"}, "Jedanaest"));
            dbHelper.addInitQuestion(new Question("Koji je službeni jezik u Gvajani?", new String[] {"Španski", "Engleski", "Portugalski", "Francuski"}, "Engleski"));
            dbHelper.addInitQuestion(new Question("Kojim slovom se u fizici obeležava ubrzanje?", new String[] {"S", "U", "T", "A"}, "A"));
            dbHelper.addInitQuestion(new Question("Koja pevačica je sa Barbadosa?", new String[] {"Madonna", "Shakira", "Rihanna", "Beyonce"}, "Rihanna"));
            dbHelper.addInitQuestion(new Question("Koje godine je umrla Milena Pavlović Barili?", new String[] {"1923.", "1945.", "1910.", "1961."}, "1945."));
            dbHelper.addInitQuestion(new Question("U kom gradu je preminuo Leonardo da Vinči?", new String[] {"U Parizu", "U Rimu", "U Amboazu", "U Firenci"}, "U Amboazu"));
            dbHelper.addInitQuestion(new Question("Šta je Australopitekus?", new String[] {"Model automobila", "Vrsta hominida", "Arhaični jezik", "Vegetativni rod"}, "Vrsta hominida"));
            dbHelper.addInitQuestion(new Question("Gde je nastao čartistički radnički pokret?", new String[] {"U Nemačkoj", "U SAD-u", "U Francuskoj", "U Velikoj Britaniji"}, "U Velikoj Britaniji"));
            dbHelper.addInitQuestion(new Question("Sajberfobija je strah od:", new String[] {"Belog luka", "Ljubljenja", "Kompjutera", "Samoće"}, "Kompjutera"));
            dbHelper.addInitQuestion(new Question("Marjaš je:", new String[] {"Metalni novac", "Nemirno dete", "Svirač", "Mađarski ples"}, "Metalni novac"));
            dbHelper.addInitQuestion(new Question("Koja od ponuđenih zemalja je najveća po površini?", new String[] {"Mađarska", "Grčka", "Srbija", "Bugarska"}, "Grčka"));
            dbHelper.addInitQuestion(new Question("Koja je najtoplija planeta sunčevog sistema?", new String[] {"Venera", "Zemlja", "Mars", "Merkur"}, "Venera"));
            dbHelper.addInitQuestion(new Question("Galerija Borgeze je jedan od najvećih muzeja:", new String[] {"Venecije", "Rima", "Milana", "Firence"}, "Rima"));
            dbHelper.addInitQuestion(new Question("Uopštenje pitagorine teoreme je:", new String[] {"Talesova teorema", "Pitagorin zakon", "Fermaova teorema", "Kosinusna teorema"}, "Kosinusna teorema"));
            dbHelper.addInitQuestion(new Question("Koji podvodni tunel je najduži na svetu?", new String[] {"Sisko u SAD", "Ispod La Manša", "Seikan u Japanu", "Između Švedske i Danske"}, "Seikan u Japanu"));
            dbHelper.addInitQuestion(new Question("Ko je igrao glavnu ulogu u filmu 'Umri muški'?", new String[] {"Bruce Willis", "Arnold Schwarzenegger", "Clint Eastwood", "Sylvester Stallone"}, "Bruce Willis"));
            dbHelper.addInitQuestion(new Question("Koliko NBA titula je osvojio Michael Jordan?", new String[] {"Tri", "Pet", "Četiri", "Šest"}, "Šest"));
            dbHelper.addInitQuestion(new Question("Ko je komponovao 'Na lepom plavom Dunavu'?", new String[] {"Štraus", "Bah", "Mocart", "Betoven"}, "Štraus"));
            dbHelper.addInitQuestion(new Question("Kakve konje je želeo Vasa Ladački u pesmi Đorđa Balaševića", new String[] {"Dorate", "Alate", "Bele", "Vrane"}, "Vrane"));
            dbHelper.addInitQuestion(new Question("John Cena je profesionalni američki:", new String[] {"Bokser", "Rvač", "Karatista", "Džudista"}, "Rvač"));
            dbHelper.addInitQuestion(new Question("Ko igra glavnu ulogu u filmu 'Jesen Samuraja'?", new String[] {"Petar Strugar", "Viktor Savić", "Nikola Kojo", "Sergej Trifunović"}, "Petar Strugar"));
            dbHelper.addInitQuestion(new Question("Koliko ima horoskopskih znakova?", new String[] {"10", "13", "11", "12"}, "12"));
            dbHelper.addInitQuestion(new Question("U crtanom filmu 'Pingvini sa Madagaskara' jedan pingvin ima isto ime kao i čin u vojsci, a to je:", new String[] {"Major", "Kapetan", "Pukovnik", "General-major"}, "Major"));
            dbHelper.addInitQuestion(new Question("Koje godine je osnovana banka Intesa Beograd?", new String[] {"1991.", "1993.", "1976", "2007."}, "1991."));
            dbHelper.addInitQuestion(new Question("Tajni agent Izzy ima ptičicu pomagača koja se zove:", new String[] {"Ogi", "Lora", "Tweety", "Ora"}, "Ogi"));
            dbHelper.addInitQuestion(new Question("Iz koje godine je film 'Pirati silikonske doline'?", new String[] {"1993.", "1996.", "1998.", "1999."}, "1999."));
            dbHelper.addInitQuestion(new Question("Kako se zove organizacija slična Crvenom krstvu u muslimanskim zemljama?", new String[] {"Al Fatah", "Crveni fes", "Crveni polumesec", "Zeleni krst"}, "Crveni polumesec"));
            dbHelper.addInitQuestion(new Question("Koliko je visok oblakoder Beograđanka?", new String[] {"101m", "73m", "152m", "203m"}, "101m"));
            dbHelper.addInitQuestion(new Question("Kako se zove najveći svetski proizvođač rajsferšlusa?", new String[] {"ZIP", "YKK", "YPP", "ZKK"}, "YKK"));
            dbHelper.addInitQuestion(new Question("Oto Hajnrih Varburg je bio nemački:", new String[] {"Astronom", "Biolog", "Inženjer", "Industrijalac"}, "Biolog"));
            dbHelper.addInitQuestion(new Question("Koji od ovih instrumenata čine ritam sekciju?", new String[] {"Bubanj i bas gitara", "Solo i ritam gitara", "Ritam i bas gitara", "Flauta i bubanj"}, "Bubanj i bas gitara"));
            dbHelper.addInitQuestion(new Question("Nauka o krvi ili:", new String[] {"Biohemija", "Patologija", "Eritologija", "Hematologija"}, "Hematologija"));
            dbHelper.addInitQuestion(new Question("Kojoj crkvi je Laza Kostić posvetio pesmu 'Santa Maria della Salute'?", new String[] {"Crkvi u Rimu", "Crkvi u Napulju", "Crkvi u Veneciji", "Crkvi u Milanu"}, "Crkvi u Veneciji"));
            dbHelper.addInitQuestion(new Question("Rod Blagojević, američki političar srpskog porekla, bio je guverner:", new String[] {"Karoline", "Ilinoisa", "Alabame", "Nevade"}, "Ilinoisa"));
            dbHelper.addInitQuestion(new Question("Koje godine je umro poznati modni kreator Iv Sen Loran?", new String[] {"1985. godine", "1980. godine", "1995. godine", "2008. godine"}, "2008. godine"));
            dbHelper.addInitQuestion(new Question("Simbol otmenosti i carske vlasti u Japanu je:", new String[] {"Hrizantema", "Orhideja", "Trešnjin cvet", "Ljubičica"}, "Hrizantema"));
            dbHelper.addInitQuestion(new Question("Gde se odvija radnja opere 'Karmen'?", new String[] {"U Egiptu", "U Maroku", "U Španiji", "U Francuskoj"}, "U Španiji"));
            dbHelper.addInitQuestion(new Question("Pol Alen je 1975. godine postao suosnivač:", new String[] {"Microsofta", "McDonald'sa", "Electronic Artsa", "Hamonda"}, "Microsofta"));
            dbHelper.addInitQuestion(new Question("Aleksandar Litvijenko, bivši potpukovnik KBG-a, je 2006. godine izgubio život nakon:", new String[] {"Saobraćajne nezgode", "Trovanja morfijumom", "Avionske nezgode", "Strujnog udara"}, "Trovanja morfijumom"));
            dbHelper.addInitQuestion(new Question("Koje godine je sagrađena i puštena u rad prva termoelektrana?", new String[] {"1896. godine", "1901. godine", "1906. godine", "1893. godine"}, "1893. godine"));
            dbHelper.addInitQuestion(new Question("Predgrađe kog grada predstavlja Grinič (Nulti meridijan)?", new String[] {"Edinburg", "Glazgov", "Kardif", "London"}, "London"));
            dbHelper.addInitQuestion(new Question("Oziris je bio egipatski bog:", new String[] {"Sunca", "Podzemnog sveta", "Proleća", "Vina"}, "Podzemnog sveta"));
            dbHelper.addInitQuestion(new Question("Ko je bio selektor fudbalske reprezentacije Srbije pre Radomira Antića?", new String[] {"Miroslav Đukić", "Ratomir Đurković", "Javier Clemente", "Ilija Petković"}, "Miroslav Đukić"));
            dbHelper.addInitQuestion(new Question("Film 'Vreme čuda' režirao je:", new String[]{"Emir Kusturica", "Želimir Žilnik", "Goran Paskaljević", "Goran Marković"}, "Goran Paskaljević"));
            dbHelper.addInitQuestion(new Question("Koja materija je najtvrđa od navedenih?", new String[] {"Gvožđe", "Dijamant", "Kobalt", "Uranijum"}, "Dijamant"));
            dbHelper.addInitQuestion(new Question("Ko peva pesmu 'Sviraj brate'?", new String[] {"Miligram", "Tropico band", "OK band", "Amadeus band"}, "Miligram"));
            dbHelper.addInitQuestion(new Question("Koje je nacionalno piće Poljske?", new String[] {"Viski", "Vinjak", "Rakija", "Vodka"}, "Vodka"));
            dbHelper.addInitQuestion(new Question("Koja od ovih zemalja nije bila u sastavu Beneluksa?", new String[] {"Luksemburg", "Belgija", "Belorusija", "Holandija"}, "Belorusija"));
            dbHelper.addInitQuestion(new Question("Kako se zvao dinosaurus ptica?", new String[] {"Triceratops", "Archeopteryx", "Brountosaurus", "Tirex"}, "Archeopteryx"));
            dbHelper.addInitQuestion(new Question("Ekstenzija .txt označava?", new String[] {"Sliku", "Prezentaciju", "Tabelu", "Tekst dokument"}, "Tekst dokument"));
            dbHelper.addInitQuestion(new Question("Grip H1N1 poznatiji je kao?", new String[] {"Ptičiji", "Svinjski", "Konjski", "Španski"}, "Svinjski"));
            dbHelper.addInitQuestion(new Question("Ime Ivan je poreklom iz:", new String[] {"Rusije", "Poljske", "Ukrajine", "Belorusije"}, "Rusije"));
            dbHelper.addInitQuestion(new Question("Kako se zove mitološko čudovište u kojem su sjedinjeni lav i orao?", new String[] {"Jednorog", "Grifon", "Minotaur", "Eaglion"}, "Grifon"));
            dbHelper.addInitQuestion(new Question("Ko je 395. godine podelio Rimsko carstvo na zapadno i istočno?", new String[] {"Justinijan", "Heraklije", "Konstantin VII", "Teodosije"}, "Teodosije"));
            dbHelper.addInitQuestion(new Question("Šta je Venerikina kosa?", new String[] {"Zvezda padalica", "Galaksija", "Sazvežđe", "Reka"}, "Sazvežđe"));
            dbHelper.addInitQuestion(new Question("Koja je prva zemlja od 01.01.2002. godine legalizovala eutanaziju?", new String[] {"Holandija", "Italija", "Francuska", "Hrvatska"}, "Holandija"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi Legoland?", new String[] {"Finska", "Danska", "Švedska", "Francuska"}, "Danska"));
            dbHelper.addInitQuestion(new Question("Za koji sport je nadležna FINA?", new String[] {"Odbojku", "Rukomet", "Plivanje", "Fudbal"}, "Plivanje"));
            dbHelper.addInitQuestion(new Question("Kako se zove atletičar kome je 1998. oduzeta zlatna medalja i poništen rekord na 100 metara?", new String[] {"Mark Fiedel", "Cris Columb", "John McEaron", "Ben Johnson"}, "Ben Johnson"));
            dbHelper.addInitQuestion(new Question("Od koga je Goran Ivanišević izgubio svoje prvo finale Wimbledona?", new String[] {"Od Federera", "Od Agassija", "Od Hewitta", "Od Raftera"}, "Od Agassija"));
            dbHelper.addInitQuestion(new Question("Scipion Afrički je pobedio Hanibala kod Zame zahvaljujući:", new String[] {"Trubama", "Lošem vremenu", "Svojim četama", "Konjima"}, "Trubama"));
            dbHelper.addInitQuestion(new Question("Ako si imao 89 riba i trećina se udavi, a ti dodaš petinu novodobijenog broja, koliko riba sada imaš?", new String[] {"89+89/3+(89/3)/5", "Nema riba", "Sve su žive", "Mnogo"}, "Sve su žive"));
            dbHelper.addInitQuestion(new Question("Koliko je lne?", new String[] {"e", "0", "2.71", "1"}, "1"));
            dbHelper.addInitQuestion(new Question("Šta je Viminacijum?", new String[] {"Trg u Rimu", "Vrsta vina", "Arheološko nalazište u Srbiji", "Vatikanski spis"}, "Arheološko nalazište u Srbiji"));
            dbHelper.addInitQuestion(new Question("Koji je najveći trocifren broj deljiv sa 3?", new String[] {"999", "636", "969", "666"}, "999"));
            dbHelper.addInitQuestion(new Question("Koja je najmanja država na svetu?", new String[] {"Luksemburg", "Vatikan", "San Marino", "Monako"}, "Vatikan"));
            dbHelper.addInitQuestion(new Question("Koji je najviši planinski vrh u Srbiji?", new String[] {"Midžor", "Crni vrh", "Pančićev vrh", "Đeravica"}, "Đeravica"));
            dbHelper.addInitQuestion(new Question("Kako se zove veština lepog i urednog pisanja?", new String[] {"Kaligrafija", "Kriptografija", "Trafografija", "Grafoskopija"}, "Kaligrafija"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi ostrvo Vido?", new String[] {"U Jadranskom moru", "U Egejskom moru", "U Jonskom moru", "U Tirenskom moru"}, "U Egejskom moru"));
            dbHelper.addInitQuestion(new Question("Prvo sedište nezavisne srpske patrijaršije je:", new String[] {"Manastir Sopoćani", "Manastir Žiča", "Pećka patrijaršija", "Manastir Studenica"}, "Manastir Žiča"));
            dbHelper.addInitQuestion(new Question("Ko je pobedio minhenski Bayern Münich u finalu fudbalske Lige Šampiona za sezonu 2012/13?", new String[] {"Borussia Dortmund", "Real Madrid", "Porto", "Barcelona"}, "Barcelona"));
            dbHelper.addInitQuestion(new Question("Autor romana 'Bornov identitet' je:", new String[] {"Robert Altman", "Robert Ladlam", "Robert Mitchum", "David Morrell"}, "Robert Ladlam"));
            dbHelper.addInitQuestion(new Question("Koja od sledećih država nije transkontinentalna?", new String[] {"Egipat", "Turska", "Mongolija", "Rusija"}, "Mongolija"));
            dbHelper.addInitQuestion(new Question("Ko je režirao filmski hit 'Avatar'?", new String[] {"Steven Spilberg", "James Cameron", "Tim Burton", "Luc Besson"}, "James Cameron"));
            dbHelper.addInitQuestion(new Question("Za koju oblast je danski naučnik Nils Bor dobio Novelovu nagradu?", new String[] {"Za biologiju", "Za medicinu", "Za fiziku", "Za hemiju"}, "Za fiziku"));
            dbHelper.addInitQuestion(new Question("Koje godine je osnovana muzička akademija u Beogradu?", new String[] {"1969.", "1804.", "1937.", "1914."}, "1937."));
            dbHelper.addInitQuestion(new Question("Kleopatra, kraljica poznata po svojoj mudrosti i lepoti, vladala je:", new String[] {"Egiptom", "Grčkom", "Persijom", "Mesopotamijom"}, "Egiptom"));
            dbHelper.addInitQuestion(new Question("Koji je naziv za poglavara katoličke crkve?", new String[] {"Kardinal", "Nadbiskup", "Papa", "Pop"}, "Papa"));
            dbHelper.addInitQuestion(new Question("Kopnena zona bezbednosti se nalazi duž administrativne linije republike Srbije sa:", new String[] {"Crnom Gorom", "Makedonijom", "Hrvatskom", "AP Kosovom i Metohijom"}, "AP Kosovom i Metohijom"));
            dbHelper.addInitQuestion(new Question("Ko je bio otac Urošu Nejakom?", new String[] {"Stefan Dečanski", "Dušan Silni", "Lazar Hrebeljanović", "Despot Stefan Lazarević"}, "Dušan Silni"));
            dbHelper.addInitQuestion(new Question("Koje je pravo ime poznate američke pevačice Lady Gage?", new String[] {"Gosselin Leah", "Marizza De Capro", "Ana Maria Gepro", "Angelina Germanotta"}, "Angelina Germanotta"));
            dbHelper.addInitQuestion(new Question("Nauka o oblicima je:", new String[] {"Morfologija", "Izometrologija", "Oblikologija", "Konturologija"}, "Morfologija"));
            dbHelper.addInitQuestion(new Question("Ko je oslobodio Tezeja iz Hada?", new String[] {"Zevs", "Herkul", "Sam se oslobodio", "Persefona"}, "Herkul"));
            dbHelper.addInitQuestion(new Question("Glavni sastojak skorupa je:", new String[] {"Paprika", "Meso", "Kupus", "Mleko"}, "Mleko"));
            dbHelper.addInitQuestion(new Question("Šta znači jurisdikcija?", new String[] {"Odsutnost", "Nadležnost", "Podeljenost", "Zastarelost"}, "Nadležnost"));
            dbHelper.addInitQuestion(new Question("Ko je policajac sa Beverli Hilsa?", new String[] {"Will Smith", "Sean Penn", "Eddie Murphy", "Bruce Willis"}, "Eddie Murphy"));
            dbHelper.addInitQuestion(new Question("Gde je održan završni turnir košarkaške Evrolige za 2013. godinu?", new String[] {"U Barseloni", "U Rimu", "U Londonu", "U Istambulu"}, "U Londonu"));
            dbHelper.addInitQuestion(new Question("U kom delu sveta se nalazi država Jemen?", new String[] {"Afrika", "Amerika", "Okeanija", "Azija"}, "Azija"));
            dbHelper.addInitQuestion(new Question("Koji od navedenih glumaca nije nagrađen Oskarom?", new String[] {"Walter Huston", "Cary Grant", "Kevin Spacey", "Louis Gossett Junior"}, "Cary Grant"));
            dbHelper.addInitQuestion(new Question("Koliko boja se nalazi na zastavi Granade?", new String[] {"5", "2", "4", "3"}, "3"));
            dbHelper.addInitQuestion(new Question("Pre izgradnje crkve Svetog Petra u Rimu, najveća hrišćanska crkva na svetu bila je:", new String[] {"Hilandar", "Moskovska patrijaršija", "Dečani", "Aja Sofija"}, "Aja Sofija"));
            dbHelper.addInitQuestion(new Question("Gde je rođen Oskar Davičo?", new String[] {"U Ljubljani", "U Zagrebu", "U Šapcu", "U Beogradu"}, "U Šapcu"));
            dbHelper.addInitQuestion(new Question("Koju grupu je osnovao basista Dušan Kojić - Koja?", new String[] {"Disciplina kičme", "EKV", "Električni orgazam", "Babe"}, "Disciplina kičme"));
            dbHelper.addInitQuestion(new Question("U kom zalivu se nalazi ostrvo na kom je umro Napoleon I Bonaparta?", new String[] {"U Boki Kotorskoj", "U Gvinejskom", "U Kvarnerskom", "U Baskijskom"}, "U Gvinejskom"));
            dbHelper.addInitQuestion(new Question("Šta je tanah?", new String[] {"Religijska knjiga", "Manjinski pokret", "Nepisani zakon", "Običajno pravo"}, "Religijska knjiga"));
            dbHelper.addInitQuestion(new Question("Šta je pesonata?", new String[] {"Engleska sobarica", "Zgrada u Dubajiju", "Vrsta papagaja", "Lekovita biljka"}, "Vrsta papagaja"));
            dbHelper.addInitQuestion(new Question("Poznata igra 'PES' je najpoznatija simulacija?", new String[] {"Fomula I", "Košarke", "Fudbala", "Ratovanja"}, "Fudbala"));
            dbHelper.addInitQuestion(new Question("Šta je Singidunum?", new String[] {"Zloglasni zatvor u SAD", "Vrsta pauka", "Romanizovano keltsko ime za Beograd", "Grčki stari naziv za Beograd"}, "Grčki stari naziv za Beograd"));
            dbHelper.addInitQuestion(new Question("Nikolaj Rimski Korsakov bio je:", new String[] {"Ruski fudbaler", "Ruski kompozitor", "Ruski fizičar", "Američki kompozitor"}, "Ruski kompozitor"));
            dbHelper.addInitQuestion(new Question("Koje su osnovne boje?", new String[] {"Crvena, plava i žuta", "Crna i bela", "Crvena, plava i zelena", "Ljubičasta, narandžasta i zelena"}, "Crvena, plava i žuta"));
            dbHelper.addInitQuestion(new Question("Konveksan znači:", new String[] {"Ravan", "Udubljen", "Ispupčen", "Ništa od navedenog"}, "Ispupčen"));
            dbHelper.addInitQuestion(new Question("Ko izvodi pesmu 'Dirli, dirli, dirlija'?", new String[] {"Leb i sol", "Crvena jabuka", "Film", "Prljavo kazalište"}, "Crvena jabuka"));
            dbHelper.addInitQuestion(new Question("Šta je ebola?", new String[] {"Zarazna bolest", "Zemljana posuda", "Bolest zuba", "Duboka, suva nizija"}, "Zarazna bolest"));
            dbHelper.addInitQuestion(new Question("Sony je kompanija iz:", new String[] {"Južne Koreje", "Kine", "Severne Koreje", "Japana"}, "Japana"));
            dbHelper.addInitQuestion(new Question("Gde je održano Svetsko prvenstvo u fudbalu 2010. godine?", new String[] {"U Urugvaju", "U Brazilu", "U Južnoj Africi", "U Rusiji"}, "U Južnoj Africi"));
            dbHelper.addInitQuestion(new Question("Za koji klub je do maja 2018. igrao španski fudbaler Andrés Iniesta Luján?", new String[] {"Barselonu", "Real Madrid", "Atletiko Madrid", "Valensiju"}, "Barselonu"));
            dbHelper.addInitQuestion(new Question("Iz koje zemlje je pobednik Eurosonga 2018. godine?", new String[] {"Austrije", "Izraela", "Ukrajine", "Kipra"}, "Izraela"));
            dbHelper.addInitQuestion(new Question("Koje godine se održalo prvo Svetsko prvenstvo u fudbalu?", new String[] {"1930. godine", "1934. godine", "1942. godine", "1938. godine"}, "1930. godine"));
            dbHelper.addInitQuestion(new Question("Koliko je dece imao Stefan Uroš I?", new String[] {"Jedno", "Dvoje", "Troje", "Četvoro"}, "Dvoje"));
            dbHelper.addInitQuestion(new Question("Koje godine je osnovana kompanija 'Frikom'?", new String[] {"1971. godine", "1987. godine", "1980. godine", "1985. godine"}, "1980. godine"));
            dbHelper.addInitQuestion(new Question("Koliko dece ima britanski princ Vilijam?", new String[] {"Dvoje", "Nema dece", "Jedno", "Troje"}, "Troje"));
            dbHelper.addInitQuestion(new Question("Koja zemlja je poznata po ružama?", new String[] {"Bugarska", "Srbija", "Rumunija", "Holandija"}, "Bugarska"));
            dbHelper.addInitQuestion(new Question("Za koji košarkaški tim igra Kyrie Irving?", new String[] {"La Lakers", "Boston Celtics", "Sacramento Kings", "Cleveland Cavaliers"}, "Boston Celtics"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi zabranjeni grad?", new String[] {"U Kairu", "U Šangaju", "U Pekingu", "U Moskvi"}, "U Pekingu"));
            dbHelper.addInitQuestion(new Question("Šta je akreditiv?", new String[] {"Punomoćje", "Dodatak", "Pozajmica", "Ugovor"}, "Punomoćje"));
            dbHelper.addInitQuestion(new Question("Koje godine je osnovana kompanija Knjaz Miloš?", new String[] {"1810.", "1811.", "1813.", "1809."}, "1811."));
            dbHelper.addInitQuestion(new Question("Ko glumi Damira Fazlinovića u seriji 'Lud, zbunjen, normalan'?", new String[] {"Moamer Kasumović", "Senad Bašić", "Mustafa Nadarević", "Emir Hadžihafizbegović"}, "Moamer Kasumović"));
            dbHelper.addInitQuestion(new Question("Na kom ostrvu je preminuo Napoleon Bonaparta?", new String[] {"Sveti Stefan", "Sveti Grgur", "Sveti Martin", "Sveta Jelena"}, "Sveta Jelena"));
            dbHelper.addInitQuestion(new Question("Dopunite naziv pesme Plavog orkestra. Lovac i?", new String[] {"Košuta", "Lane", "Srna", "Jelen"}, "Košuta"));
            dbHelper.addInitQuestion(new Question("Kako se zove predsednik SAD (2016. godina)?", new String[] {"Donald Trump", "Barack Obama", "Hillary Clinton", "Marco Rubio"}, "Donald Trump"));
            dbHelper.addInitQuestion(new Question("Ko se smatra ocem istorije?", new String[] {"Tukidid", "Herodot", "Amijan Parcelin", "Eunapije iz Sarda"}, "Herodot"));
            dbHelper.addInitQuestion(new Question("Koliko godina ima Julija u Šekspirovoj drami 'Romeo i Julija'?", new String[] {"13", "15", "17", "12"}, "13"));
            dbHelper.addInitQuestion(new Question("U kom manastiru na Svetoj gori se zamonašio Rastko Nemanjić?", new String[] {"Vatopedu", "Hilandaru", "Velikoj Lavri", "Sv. Panteleimonu"}, "Sv. Panteleimonu"));
            dbHelper.addInitQuestion(new Question("Džastin Frankel je osmislio:", new String[] {"Google", "Winamp", "Windows XP", "Facebook"}, "Winamp"));
            dbHelper.addInitQuestion(new Question("Biljka Šumarica je?", new String[] {"Sasa", "Kukurek", "Nana", "Paprat"}, "Sasa"));
            dbHelper.addInitQuestion(new Question("Šta je Kaspersky?", new String[] {"Kompjuterski virus", "Kompjuterski program", "Kompjuterski antivirus", "Operativni sistem"}, "Kompjuterski antivirus"));
            dbHelper.addInitQuestion(new Question("DJ je?", new String[] {"Dance Jockey", "Disk Jockey", "Dance Jukebox", "Disk Jukebox"}, "Disk Jockey"));
            dbHelper.addInitQuestion(new Question("Sa kojim državama se graniči republika Nikaragva?", new String[] {"Hondurasom i Kostarikom", "Tanzanijom, Ugandom, Sudanom, Etiopijom i Somalijom", "Tajlandom, Laosom i Vijetnamom", "Peruom, Bolivijom i Argentinom"}, "Hondurasom i Kostarikom"));
            dbHelper.addInitQuestion(new Question("Ko je snimio album 'Kind of Blue'?", new String[] {"Dizzy Gillespie", "Miles Davis", "Louis Armstrong", "John Coltrane"}, "Miles Davis"));
            dbHelper.addInitQuestion(new Question("Na kom kontinentu se nalazi Gvajana?", new String[] {"Azija", "Južna Amerika", "Afrika", "Severna Amerika"}, "Južna Amerika"));
            dbHelper.addInitQuestion(new Question("Ko je napisao naučno-fantastični roman 'Nineteen eighty-four (1984)'?", new String[] {"Benjamin Disrael", "Mark Twain", "Geogre Orwell", "Charles Dickens"}, "Geogre Orwell"));
            dbHelper.addInitQuestion(new Question("U kom klubu je David Backham završio karijeru?", new String[] {"Los Angeles Galaxy", "Manchester United", "Real Madrid", "Paris Saint-Germain"}, "Paris Saint-Germain"));
            dbHelper.addInitQuestion(new Question("Koje životinje predu osim mačaka?", new String[] {"Nilski konji", "Žirafe", "Veverice", "Zebre"}, "Veverice"));
            dbHelper.addInitQuestion(new Question("Koja država je prva počela da koristi papirne novčanice?", new String[] {"Kina", "Indija", "Egipat", "Portugalija"}, "Kina"));
            dbHelper.addInitQuestion(new Question("Koja je najveća životinja na svetu?", new String[] {"Slon", "Plavi kit", "Žirafa", "Zelena anakonda"}, "Plavi kit"));
            dbHelper.addInitQuestion(new Question("Glavni grad Kolumbije je?", new String[] {"Managua", "Medellin", "Bogota", "Tijuana"}, "Bogota"));
            dbHelper.addInitQuestion(new Question("Nekada se zvala Burma, o kojoj državi je reč?", new String[] {"Mjanmar", "Šri Lanka", "Laos", "Bangladeš"}, "Mjanmar"));
            dbHelper.addInitQuestion(new Question("Kako se zvao Muhammed Ali pre nego što je promenio ime?", new String[] {"Cassius Marcellus Clay, Jr", "Kareem Abdul-Jabbar", "Bobby Johnson", "Carl Weathers"}, "Cassius Marcellus Clay, Jr"));
            dbHelper.addInitQuestion(new Question("U kojoj državi se nalazi Angkor Wat, najveći religijski hram na svetu?", new String[] {"Tajland", "Vijetnam", "Peru", "Kambodža"}, "Kambodža"));
            dbHelper.addInitQuestion(new Question("Pre nego što je započeo solo karijeru Sting je bio glavni tekstopisac, basista i pevač jedne rok grupe. O kojoj grupi je reč?", new String[] {"The Who", "Oasis", "The Police", "The Clash"}, "The Police"));
            dbHelper.addInitQuestion(new Question("Machu Picchu je sveti grad kog drevnog naroda?", new String[] {"Inka", "Maja", "Asteka", "Tolteka"}, "Inka"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi Mikronezija?", new String[] {"U Atlanskom okeanu", "U  Indijskom okeanu", "U severnom ledenom okeanu", "U Tihom okeanu"}, "U Tihom okeanu"));
            dbHelper.addInitQuestion(new Question("Čega se plaše akrofobični ljudi?", new String[] {"Uskog prostora", "Visine", "Zmija", "Paukova"}, "Visine"));
            dbHelper.addInitQuestion(new Question("U kom romanu britanskog pisca Iana Fleminga se prvi put pojavio James Bond?", new String[] {"Casino Royale", "Live and let die", "Diamonds are forever", "From Russia with love"}, "Casino Royale"));
            dbHelper.addInitQuestion(new Question("U kom gradu se nalazi Bazilika sv. Marka?", new String[] {"U Madridu", "U Rimu", "U Barseloni", "U Veneciji"}, "U Veneciji"));
            dbHelper.addInitQuestion(new Question("Ko je nasledio kneza Miloša na čelu Srbije 1839. godine?", new String[] {"Aleksandar Karađorđević", "Aleksandar Obrenović", "Milan Obrenović", "Mihailo Obrenović"}, "Milan Obrenović"));
            dbHelper.addInitQuestion(new Question("Dobitnik FIFA nagrade za najboljeg fudbalera 2018. godine je?", new String[] {"Ivan Rakitić", "Lionel Messi", "Cristiano Ronaldo", "Luka Modrić"}, "Luka Modrić"));
            dbHelper.addInitQuestion(new Question("Gde se nalazi planina Kilimandžaro?", new String[] {"U Tanzaniji", "U Keniji", "U Etiopiji", "U Somaliji"}, "U Tanzaniji"));
            dbHelper.addInitQuestion(new Question("Kroz koji grad protiče reka Neva?", new String[] {"Kroz Moskvu", "Kroz Sankt Petersburg", "Kroz Kalinjingrad", "Kroz Kazanj"}, "Kroz Sankt Petersburg"));
            dbHelper.addInitQuestion(new Question("Ko je napisao 'Za kim zvona zvone'?", new String[] {"Charles Dickens", "Erich Maria Remark", "Jules Verne", "Ernest Hemingway"}, "Ernest Hemingway"));
            dbHelper.addInitQuestion(new Question("U kojoj državi je rođen Adolf Hitler?", new String[] {"U Pruskoj", "U Austriji", "U Nemačkoj", "U Italiji"}, "U Austriji"));
            dbHelper.addInitQuestion(new Question("Ksenofobija je strah od?", new String[] {"Stranaca", "Visine", "Dubine", "Otvorenog prostora"}, "Stranaca"));
            dbHelper.addInitQuestion(new Question("Glavni grad Nepala je:", new String[] {"Islamabad", "Katmandu", "Pešavar", "Lasa"}, "Katmandu"));
            dbHelper.addInitQuestion(new Question("Iz kog jezika potiče reč juvelir?", new String[] {"Iz holandskog", "Iz belgijskog", "Iz novrveškog", "Iz češkog"}, "Iz holandskog"));
            dbHelper.addInitQuestion(new Question("Izvođač pesme 'Piješ sine' je?", new String[] {"Lexington band", "Tropico band", "Dženan Lončarević", "Željko Joksimović"}, "Dženan Lončarević"));
            dbHelper.addInitQuestion(new Question("Izbacite uljeza:", new String[] {"Huawei P20", "Huawei P20 Lite", "Huawei P20 Pro", "Huawei P20 Mate"}, "Huawei P20 Mate"));
            dbHelper.addInitQuestion(new Question("U seriji 'Nemanjići - rađanje kraljevine' lik druge supruge Stefana Prvovenčanog tumači?", new String[] {"Dubravka Mijatović", "Sloboda Mićalović", "Jelena Gavrilović", "Nada Šargin"}, "Sloboda Mićalović"));
            dbHelper.addInitQuestion(new Question("Osveta je jelo koje se servira...?", new String[] {"Toplo", "Sirovo", "Kuvano", "Hladno"}, "Hladno"));
            dbHelper.addInitQuestion(new Question("Kada neko igra fudbal žinga (ginga) stilom, on je verovatno iz?", new String[] {"Kine", "Brazila", "Argentine", "Portugala"}, "Brazila"));
            dbHelper.addInitQuestion(new Question("Šta je Natalijina Ramonda?", new String[] {"Simbol velikog neprijatelja", "Šareni vez na donjem rubu damske haljine u 19. veku", "Prsluk koji mlada nosi prve bračne noći", "Cvet feniksa - simbol dana primirja u Prvom svetskom ratu"}, "Cvet feniksa - simbol dana primirja u Prvom svetskom ratu"));
            dbHelper.addInitQuestion(new Question("Ko je otkrio Lepenski vir?", new String[] {"Dragoslav Srejović", "Milorad M. Vasić", "Willard Libby", "John Aubrey"}, "Dragoslav Srejović"));
            dbHelper.addInitQuestion(new Question("Koje godine se odigrala bitka kod Tanenberga?", new String[] {"1815.", "1878.", "1914.", "1943."}, "1914."));
            dbHelper.addInitQuestion(new Question("Paul Klee se proslavio kao?", new String[] {"Doktor", "Slikar", "Pisac", "Kompozitor"}, "Slikar"));
            dbHelper.addInitQuestion(new Question("Kom slivu pripada reka Drina?", new String[] {"Crnomorskom", "Egejskom", "Severnomorkom", "Jadranskom"}, "Crnomorskom"));
            dbHelper.addInitQuestion(new Question("'Brankovo kolo' je dobilo ime po pesniku Branku:", new String[] {"Rakiću", "Iliću", "Antiću", "Radičeviću"}, "Radičeviću"));
            dbHelper.addInitQuestion(new Question("Ko je napisao pripovetku 'Sve će to narod pozlatiti'?", new String[] {"Vladislav Petković Dis", "Branislav Nušić", "Laza Lazarević", "Ivo Andrić"}, "Laza Lazarević"));
            dbHelper.addInitQuestion(new Question("Koga je ubio Jack Ruby?", new String[] {"Lee Harvey Oswalda", "Johna Lennona", "Marka Davida Chapmana", "Johna Kennedya"}, "Lee Harvey Oswalda"));
            dbHelper.addInitQuestion(new Question("Koja država je kolevka sladoleda?", new String[] {"Italija", "Engleska", "Kina", "Ujedinjeni Arapski Emirati"}, "Kina"));
            dbHelper.addInitQuestion(new Question("Koje godine je napravljen prvi kornet?", new String[] {"1924.", "1923.", "1925.", "1930."}, "1924."));
            dbHelper.addInitQuestion(new Question("Kada je napravljen prvi sladoled na štapiću?", new String[] {"1930.", "1934.", "1935.", "1940."}, "1934."));
            dbHelper.addInitQuestion(new Question("Koji padež odgovara na pitanja 'koga, šta'?", new String[] {"Dativ", "Lokativ", "Instrumental", "Akuzativ"}, "Akuzativ"));
            dbHelper.addInitQuestion(new Question("Koja od sledećih država nije članica EU?", new String[] {"Švedska", "Finska", "Švajcarska", "Litvanija"}, "Švajcarska"));
            dbHelper.addInitQuestion(new Question("Kojom zemljom je vladao Vlad III Cepeš?", new String[] {"Rumunijom", "Bugarskom", "Mađarskom", "Hrvatskom"}, "Rumunijom"));
            dbHelper.addInitQuestion(new Question("Koliko ima krugova pakla u delu Dantea Aligijerija 'Božanstvena komedija'?", new String[] {"Dvanaest", "Sedam", "Devet", "Osam"}, "Devet"));
            dbHelper.addInitQuestion(new Question("Glavni grad EU je?", new String[] {"Berlin", "Brisel", "Luksemburg", "Pariz"}, "Brisel"));
            dbHelper.addInitQuestion(new Question("Šta su ligature?", new String[] {"Grafički znakovi dobijeni spajanjem dva ili tri slova", "Ukrasne minijature na sakralnim objektima", "Oznake na turističkim mapama", "Delovi u liturgiji koji se ponavljaju"}, "Grafički znakovi dobijeni spajanjem dva ili tri slova"));
            dbHelper.addInitQuestion(new Question("Koje godine je preminuo Fidel Kastro?", new String[] {"2010.", "2011.", "2016.", "2017."}, "2016."));
            dbHelper.addInitQuestion(new Question("Koja krvna grupa je univerzalni davalac?", new String[] {"A", "AB", "0", "B"}, "0"));
            dbHelper.addInitQuestion(new Question("Radetzky marš napisao je?", new String[] {"Johan Štraus stariji", "Johan Štraus mlađi", "Johan Sebastian Bah", "Eugen J. Bah"}, "Johan Štraus stariji"));
            dbHelper.addInitQuestion(new Question("Ko igra glavnu mušku ulogu u filmu 'Kazablanka'?", new String[] {"Rock Hudston", "Humphrey Bogart", "John Wayne", "Gregory Peck"}, "Humphrey Bogart"));
            dbHelper.addInitQuestion(new Question("Glavna glumica u filmu 'Kazablanka' je?", new String[] {"Joy Page", "Madeleine Lebeau", "Ilka Grüning", "Ingrid Bergman"}, "Ingrid Bergman"));
            dbHelper.addInitQuestion(new Question("Drugi deo kog filmskog serijala je poznat pod nazivom 'Drumski ratnik'?", new String[] {"Smrtonosno oružje", "Pobesneli Maks", "Terminator", "Umri muški"}, "Pobesneli Maks"));
            dbHelper.addInitQuestion(new Question("Askja, Hekla i Katla su imena islandskih?", new String[] {"Vulkana", "Planina", "Gradova", "Luka"}, "Vulkana"));
            dbHelper.addInitQuestion(new Question("Kako se zove album Dina Dvornika iz 1993. godine?", new String[] {"Kreativni nered", "Pandorina kutija", "Priroda i društvo", "Enfant terrible"}, "Priroda i društvo"));
            dbHelper.addInitQuestion(new Question("Šta je kod Czeslawa Milosza zarobljeno, a kod Imanuela Kanta čisto i praktično?", new String[] {"Sila", "Energija", "Znanje", "Um"}, "Um"));
            dbHelper.addInitQuestion(new Question("Bacil je bakterija kog oblika?", new String[] {"Kuglice", "Štapića", "Grozda", "Spirale"}, "Štapića"));
            dbHelper.addInitQuestion(new Question("Kako se zove žabac u komediji 'The Muppets'?", new String[] {"Kermit", "Ralf", "Gonzo", "Waldorf"}, "Kermit"));
            dbHelper.addInitQuestion(new Question("Sa kojom pesmom je grupa 'Novi fosili' na Evroviziji 1987. godine osvojila 4. mesto?", new String[] {"Mangup", "Željo moja", "Rock me baby", "Ja sam za ples"}, "Ja sam za ples"));
            dbHelper.addInitQuestion(new Question("Anglofobija je strah od?", new String[] {"Životinja", "Uglova", "Svemira", "Engleza"}, "Engleza"));
            dbHelper.addInitQuestion(new Question("Koji junak je poznat kao 'Zmaj od Noćaja'?", new String[] {"Ilija Garašanin", "Stojan Čupić", "Bajo Pivljanin", "Jovan Jovanović"}, "Stojan Čupić"));
            dbHelper.addInitQuestion(new Question("Koje godine je otkrivena planeta Uran?", new String[] {"1876.", "1918.", "1871.", "1817."}, "1871."));
            dbHelper.addInitQuestion(new Question("Za koji od ponuđenih timova nikada nije igrao Ferenc Puskás?", new String[] {"Torino", "Real Madrid", "Honvéd", "Kišpešt"}, "Torino"));
            dbHelper.addInitQuestion(new Question("Koje godine je Stefan Nemanja otišao na Svetu Goru?", new String[] {"1198.", "1196.", "1197.", "1194."}, "1197."));
            dbHelper.addInitQuestion(new Question("Koje je nacionalno piće Kube?", new String[] {"Viski", "Tekila", "Pivo", "Rum"}, "Rum"));
            dbHelper.addInitQuestion(new Question("Potamologija je nauka o?", new String[] {"Jezerima", "Rekama", "Pećinama", "Okeanima"}, "Rekama"));
            dbHelper.addInitQuestion(new Question("Koji jezik se govori na Kubi?", new String[] {"Havajski", "Portugalski", "Kubanski", "Španski"}, "Španski"));
            dbHelper.addInitQuestion(new Question("U kojoj još grupi je svirao Koja iz 'Discipline kičme'?", new String[] {"Paraf", "Šarlo akrobata", "Bijelo Dugme", "Pankrti"}, "Šarlo akrobata"));
            dbHelper.addInitQuestion(new Question("Kako se zove košarkaš koji je 1992. godine u dresu Partizana postigao odlučujuću trojku za Kup šampiona?", new String[] {"Predrag Danilović", "Aleksandar Đorđević", "Vlade Divac", "Žarko Paspalj"}, "Aleksandar Đorđević"));
            dbHelper.addInitQuestion(new Question("Kojoj državi pripada ostrvo Lanzarote?", new String[] {"Španiji", "Italiji" , "Meksiku", "Portugaliji"}, "Španiji"));
            dbHelper.addInitQuestion(new Question("Koji od sledećih hemijskih elemenata se ne nalazi u sastavu limunske kiseline?", new String[] {"Kiseonik", "Vodonik", "Azot", "Ugljenik"}, "Azot"));
            dbHelper.addInitQuestion(new Question("Šta je po zanimanju bio Vasa Pelagić?", new String[] {"Geometar", "Učitelj", "Lekar", "Sveštenik"}, "Učitelj"));
            dbHelper.addInitQuestion(new Question("Kako se naziva sila koja predstavlja delovanje dve ili više sila?", new String[] {"Rezultanta", "Zbirna sila", "Skalarna", "Vektorska"}, "Rezultanta"));
            dbHelper.addInitQuestion(new Question("Koliko godina je trajalo II fracusko carstvo?", new String[] {"18", "20", "19", "36"}, "19"));
            dbHelper.addInitQuestion(new Question("Kroz koju državu protiče reka Jenisej?", new String[] {"Avganistan", "Ukrajinu", "Belgiju", "Rusiju"}, "Rusiju"));
            dbHelper.addInitQuestion(new Question("Ko je šesta zvezdina zvezda?", new String[] {"Darko Pančev", "Rajko Mitić", "Generacija iz 1991. godine", "Dragan Stojković Piksi"}, "Generacija iz 1991. godine"));
            dbHelper.addInitQuestion(new Question("Šta je oskoruša?", new String[] {"Vrsta drveta", "Sušena riba", "Vrsta cveća", "Reka koja presuši"}, "Vrsta drveta"));
            dbHelper.addInitQuestion(new Question("Koje godine je rođen Zvonko Bogdan?", new String[] {"1950.", "1941.", "1942.", "1949."}, "1942."));
            dbHelper.addInitQuestion(new Question("Do koliko stepeni može biti visoka temperatura na mestu električnog pražnjenja u atmosferi?", new String[] {"1.000 stepeni", "55.000 stepeni", "20.000 stepeni", "10.000 stepeni"}, "20.000 stepeni"));
            dbHelper.addInitQuestion(new Question("Ono što je za Rim bio Koloseum, za Carigrad je?", new String[] {"Arena", "Hipodrom", "Aja Sofija", "Zlatni rog"}, "Hipodrom"));
            dbHelper.addInitQuestion(new Question("Najveća riba na svetu je?", new String[] {"Kit ajkula", "Plavi kit", "Morski pas", "Amazonski grgeč"}, "Kit ajkula"));
            dbHelper.addInitQuestion(new Question("Koje boje je planeta Mars?", new String[] {"Plave", "Žute", "Crvene", "Narandžaste"}, "Crvene"));
            dbHelper.addInitQuestion(new Question("Kako se stručno naziva zaštitnik prava građana?", new String[] {"Advokat", "Pravobranilac", "Ombudsman", "Poslanik"}, "Ombudsman"));
            dbHelper.addInitQuestion(new Question("Mačkov kamen je najviši vrh jedne planine. O kojoj planini je reč?", new String[] {"Jagodnji", "Maljenu", "Povlenu", "Suvoboru"}, "Jagodnji"));
            dbHelper.addInitQuestion(new Question("Koliko žica ima akustična gitara?", new String[] {"4", "6", "5", "7"}, "6"));
            dbHelper.addInitQuestion(new Question("Koliko dana je trajala Pariska komuna?", new String[] {"49", "279", "72", "125"}, "72"));
            dbHelper.addInitQuestion(new Question("Koja reka protiče kroz Grdeličku klisuru?", new String[] {"Ibar", "Resava", "Vlasina", "Morava"}, "Morava"));
            dbHelper.addInitQuestion(new Question("Izbacite marku koja ne pripada istoj kompaniji.", new String[] {"Converse", "Puma", "Umbro", "Nike"}, "Puma"));
            dbHelper.addInitQuestion(new Question("Šta u predvodu sa latinskog znači 'Una hirunda non facit ver'?", new String[] {"Jedna lasta ne čini proleće", "Mi o vuku, a vuk na vrata", "Sve svoje nosim sa sobom", "Kad na vrbi rodi grožđe"}, "Jedna lasta ne čini proleće"));
            dbHelper.addInitQuestion(new Question("Koja od navedenih čokoladica u sebi sadrži keks?", new String[] {"Mars", "Snickers", "Twix", "Kidy"}, "Twix"));
            dbHelper.addInitQuestion(new Question("Dovršite naziv benda: Nick Cave and?", new String[] {"The bad seeds", "The sailors", "The stooges", "The wailers"}, "The bad seeds"));
            dbHelper.addInitQuestion(new Question("'Nisam se oženio baš zato što cenim žene' rečenica je koju je izgovorio poznati filozof?", new String[] {"Zarathustra", "Friedrich Wilhelm Nietzsche", "Arthur Schopenhauer", "Khalil Gibran"}, "Friedrich Wilhelm Nietzsche"));
            dbHelper.addInitQuestion(new Question("Neologizam je?", new String[] {"Novo učenje", "Logičko pravilo", "Nova reč", "Nova pojava"}, "Nova reč"));
            dbHelper.addInitQuestion(new Question("Šta je po zanimanju bio Loius Armstrong?", new String[] {"Astronaut", "Glumac", "Predsednik SAD", "Muzičar"}, "Muzičar"));
            dbHelper.addInitQuestion(new Question("Koji od sledećih gradova se ne nalazi na pruzi Beograd-Bar?", new String[] {"Čačak", "Požega", "Užice", "Kosjerić"}, "Čačak"));
            dbHelper.addInitQuestion(new Question("Danilo Nikolić je poznati?", new String[] {"Glumac", "Muzičar", "Književnik", "Reditelj"}, "Književnik"));
            dbHelper.addInitQuestion(new Question("Kako se naziva verovanje u boga u racionalnom smislu, bez vezivanja za određenu religiju?", new String[] {"Budizam", "Deizam", "Ateizam", "Pluralizam"}, "Deizam"));
            dbHelper.addInitQuestion(new Question("Kada je Kraljevina Jugoslavija pristupila Trojnom paktu?", new String[] {"1941. godine", "1939. godine", "1940. godine", "1942. godine"}, "1941. godine"));
            dbHelper.addInitQuestion(new Question("Na kom brodu je propisana kapitulacija Japana u Drugom svetskom ratu?", new String[] {"Pacifik", "Misisipi", "Atlantik", "Misuri"}, "Misuri"));
            dbHelper.addInitQuestion(new Question("Koja od sledećih grupa ostrva se ne nalazi u Indijskom okeanu?", new String[] {"Komorska ostrva", "Sejšelska ostrva", "Kurilska ostrva", "Maldivi"}, "Kurilska ostrva"));
            dbHelper.addInitQuestion(new Question("Mesto gde je Isus razapet je?", new String[] {"Nazaret", "Vitlajem", "Golgota", "Jordan"}, "Golgota"));
            dbHelper.addInitQuestion(new Question("Drugi naziv za nevoljno drhtanje tela je?", new String[] {"Tremor", "Drhtavica", "Atrofija", "Katapleksija"}, "Tremor"));
            dbHelper.addInitQuestion(new Question("'Sve iz inata' hit je grupe?", new String[] {"Divlje jagode", "Osvajači", "Riblja čorba", "Babe"}, "Divlje jagode"));
            dbHelper.addInitQuestion(new Question("Pozivni broj za Negotin je?", new String[] {"016", "019", "017", "020"}, "019"));
            dbHelper.addInitQuestion(new Question("Niz koji ima graničnu vrednosti je?", new String[] {"Konvergentan", "Divergentan", "Aritmetički", "Iracionalan"}, "Konvergentan"));
            dbHelper.addInitQuestion(new Question("U kom sportu se proslavio Momir Petković?", new String[] {"Džudou", "Karateu", "Boksu", "Rvanju"}, "Rvanju"));
            dbHelper.addInitQuestion(new Question("Gde živi jedina vrsta slatkovodne foke na svetu?", new String[] {"U Sargaskom moru", "U La manšu", "Bajkalskom jezeru", "U koritu Volge"}, "Bajkalskom jezeru"));
            dbHelper.addInitQuestion(new Question("Konačni poraz Napoleona kod Vaterloa dogodio se?", new String[] {"1815. godine", "1812. godine", "1821. godine", "1818. godine"}, "1815. godine"));
            dbHelper.addInitQuestion(new Question("Ko je izgovorio 'Eureka!'?", new String[] {"Aleksandar Makedonski", "Archimedes", "Aristoteles", "Einstein"}, "Archimedes"));
            dbHelper.addInitQuestion(new Question("Kako se zvao čovek za kog se udala Jacqueline Kennedy nakon atentata na supruga?", new String[] {"Konstantin Micotakis", "Konstantinos Karamanlis", "Aristotelis Onassis", "David Rockefeller"}, "Aristotelis Onassis"));
            dbHelper.addInitQuestion(new Question("Šta je po veroispovesti bio Mohandas Karamchand Gandhi?", new String[] {"Ateista", "Musliman", "Budista", "Hindus"}, "Hindus"));
            dbHelper.addInitQuestion(new Question("Glavni grad američke savezne države Illinois je?", new String[] {"Sacramento", "Chicago", "Las Vegas", "Springfield"}, "Springfield"));
            dbHelper.addInitQuestion(new Question("Kada se odigrala Borodinska bitka?", new String[] {"1812. godine", "1782. godine", "1839. godine", "1917. godine"}, "1812. godine"));
            dbHelper.addInitQuestion(new Question("Koji od sledećih astroloških zankova pripada grupi zemljanih?", new String[] {"Vaga", "Bik", "Rak", "Vodolija"}, "Bik"));
            dbHelper.addInitQuestion(new Question("Šta je kuglof?", new String[] {"Vrsta plesa", "Plemićka titula", "Zamak", "Vrsta kolača"}, "Vrsta kolača"));
            dbHelper.addInitQuestion(new Question("Koji kolumbijski pevač je pevao na otvaranju Mundijala 2010. godine u Južnoj Africi?", new String[] {"Martin", "Juanes", "Kardoso", "Eskobar"}, "Juanes"));
            dbHelper.addInitQuestion(new Question("Koliki je maksimalan broj rundi u profesionalnom boks meču?", new String[] {"12", "10", "4", "11"}, "12"));
            dbHelper.addInitQuestion(new Question("Kozaci su bili upamćeni kao konjanici koji su ratovali za interese?", new String[] {"Turske", "Kine", "Ruske imperije", "Mongolije"}, "Ruske imperije"));
            dbHelper.addInitQuestion(new Question("Na kom univerzitetu je predavao Mihajlo Pupin?", new String[] {"Sorbonne", "Stanford", "Yale", "Columbia"}, "Columbia"));
            dbHelper.addInitQuestion(new Question("Kako se zove slikar koji je naslikao plakat za film 'Bitka na Neretvi'?", new String[] {"Sava Šumanović", "Uroš Predić", "Pablo Picasso", "Uroš Đurić"}, "Pablo Picasso"));
            dbHelper.addInitQuestion(new Question("Koje nacionalnosti je tvorac Rubikove kocke?", new String[] {"Mađarske", "Češke", "Poljske", "Rumunske"}, "Mađarske"));
            dbHelper.addInitQuestion(new Question("Prvi album pevačice Adele je?", new String[] {"Music", "21", "Love", "19"}, "19"));
            dbHelper.addInitQuestion(new Question("Ko je pravio violine?", new String[] {"Giovanni", "Galliani", "Amati", "Mastroianni"}, "Amati"));
            dbHelper.addInitQuestion(new Question("Odakle je pisac i istoričar Mikhaēl Psellos?", new String[] {"Iz Češke", "Iz Vizantije", "Iz Bugarske", "Iz Slovačke"}, "Iz Vizantije"));
            dbHelper.addInitQuestion(new Question("Édson Arantes do Nascimento ili?", new String[] {"Pelé", "Ronaldo", "Zico", "Sócrates"}, "Pelé"));
            dbHelper.addInitQuestion(new Question("Sposobnost nekog tela da vrši rad u fizici se naziva?", new String[] {"Potisak", "Napon", "Intercija", "Energija"}, "Energija"));
            dbHelper.addInitQuestion(new Question("Koliko je trajao let Challengera 1986. godine?", new String[] {"25 minuta", "78 sekundi", "65 sati", "87 dana"}, "78 sekundi"));
            dbHelper.addInitQuestion(new Question("Organizacija za obrazovanje, kulturu i nauku pod okriljem UN zove se?", new String[] {"WHO", "Milenijum", "UNHCR", "UNESCO"}, "UNESCO"));
            dbHelper.addInitQuestion(new Question("Šta je anekumena?", new String[] {"Nenaseljena oblast", "Naseljena oblast", "Prostrana travnata površina", "Vasionsko telo"}, "Nenaseljena oblast"));
            dbHelper.addInitQuestion(new Question("Čuma je narodni naziv za koju bolest?", new String[] {"Tifus", "Malariju", "Kugu", "Velike boginje"}, "Kugu"));
            dbHelper.addInitQuestion(new Question("Ko se budi u pesmi Šarla Akrobate?", new String[] {"On", "Ona", "Olja", "Magi"}, "Ona"));
            dbHelper.addInitQuestion(new Question("Koje godine je počela sa radom hidroelektrana Zvornik?", new String[] {"1960. godine", "1948. godine", "1955. godine", "1963. godine"}, "1955. godine"));
            dbHelper.addInitQuestion(new Question("Za koji italijanski klub je igrao Maradona?", new String[] {"Inter", "Milan", "Juventus", "Napoli"}, "Napoli"));
            dbHelper.addInitQuestion(new Question("U kom mestu je rođen Adolf Hitler?", new String[] {"U Bremenu", "U Leipzigu", "U Münichu", "U Braunau"}, "U Braunau"));
            dbHelper.addInitQuestion(new Question("Emetofobija je strah od?", new String[] {"Liftova", "Povraćanja", "Prelaska ulice", "Sireva"}, "Povraćanja"));
            dbHelper.addInitQuestion(new Question("Koje je pravo ime strip junaka Zagora?", new String[] {"Patrick Wilding", "Wandercy Fitzy", "Doc Lester", "Salomen Kinsky"}, "Patrick Wilding"));
            dbHelper.addInitQuestion(new Question("Koje godine se Bangladeš otcepio od Pakistana?", new String[] {"1946.", "1948.", "1971.", "1915."}, "1971."));
            dbHelper.addInitQuestion(new Question("U kojoj saveznoj američkoj državi se nalazi San Francisco?", new String[] {"U Arizoni", "U Texasu", "U Californiji", "U Tennesseeu"}, "U Californiji"));
            dbHelper.addInitQuestion(new Question("Akvavit je?", new String[] {"Vrsta pumpe", "Alkoholno piće", "Gusti voćni sok", "Kisela voda"}, "Alkoholno piće"));
            dbHelper.addInitQuestion(new Question("Koliko iznosi napon u evropskim električnim mrežama?", new String[] {"220 Volti", "220 Watti", "220 Ampera", "220 Tesli"}, "220 Volti"));
            dbHelper.addInitQuestion(new Question("Babin zub se nalazi u blizini?", new String[] {"Kragujevca", "Kruševca", "Majdanpeka", "Knjaževca"}, "Knjaževca"));
            dbHelper.addInitQuestion(new Question("1/tangens ili?", new String[] {"Kotanges", "Arkus kosinus", "Tanges hiperbolični", "Arkus tangens"}, "Kotanges"));
            dbHelper.addInitQuestion(new Question("Čija je pesma 'Devojka iz grada'?", new String[] {"Marinka Rokvića", "Predraga Živkovića Tozovca", "Miroslava Ilića", "Tome Zdravkovića"}, "Miroslava Ilića"));
            dbHelper.addInitQuestion(new Question("Koji instrument je svirao Željko Joksimović pre nego što je počeo da peva i komponuje?", new String[] {"Orgulje", "Harmoniku", "Klavir", "Trubu"}, "Harmoniku"));
            dbHelper.addInitQuestion(new Question("Za najboljeg igrača EP u košarci 2007. godine proglašen je?", new String[] {"Predrag Stojaković", "Dirk Nowitzki", "Pau Gasol", "Андрей Кириленко"}, "Андрей Кириленко"));
            dbHelper.addInitQuestion(new Question("Koje godine je izmišljen tranzistor?", new String[] {"1739.", "1833.", "1930.", "1947."}, "1947."));
            dbHelper.addInitQuestion(new Question("Koji je prvi srpski zvučni film?", new String[] {"Slavica", "Nevinost bez zaštite", "Rudareva sreća", "Grešnica bez greha"}, "Nevinost bez zaštite"));
            dbHelper.addInitQuestion(new Question("Šta je dženaza?", new String[] {"Sahrana", "Svadba", "Bolest", "Grad"}, "Sahrana"));
            dbHelper.addInitQuestion(new Question("Kako se zvala rimska boginja zemljoradnje?", new String[] {"Minerva", "Vesta", "Justicija", "Prozerpina"}, "Prozerpina"));
            dbHelper.addInitQuestion(new Question("Koje je bilo svetovno ime Dositeja Obradovića?", new String[] {"Danilo", "Dušan", "Dimitrije", "David"}, "Dimitrije"));
            dbHelper.addInitQuestion(new Question("Ko je napisao knjigu 'Psihopatologija svakodnevnog života'?", new String[] {"Carl Gustav Jung", "Erich Fromm", "Friedrich Nietzsche", "Sigmund Freud"}, "Sigmund Freud"));
            dbHelper.addInitQuestion(new Question("Kako se naziva mehanizam koji omogućava biljci da rastvorene hranljive materije iz zemlje dovede do lista?", new String[] {"Fotosinteza", "Osmoza", "Fitokineza", "Fitoliza"}, "Osmoza"));
            dbHelper.addInitQuestion(new Question("Kako se ranije zvao Zimbabve?", new String[] {"Rodezija", "Dahomej", "Zair", "Gornja Volta"}, "Rodezija"));
            dbHelper.addInitQuestion(new Question("Kako se zove glumica koja tumači glavnu ulogu u filmu 'Resident Evil'?", new String[] {"Anica Dobra", "Audrey Hepburn", "Kate Beckett", "Milla Jovovich"}, "Milla Jovovich"));
            dbHelper.addInitQuestion(new Question("Šta je bobija?", new String[] {"Planina blizu Ljubovije", "Koštuljičavo voće", "Nalazište kamenog uglja", "Srednjovekovni grad"}, "Planina blizu Ljubovije"));
            dbHelper.addInitQuestion(new Question("Koja od navedenih reka nije pritoka Save?", new String[] {"Vrbas", "Kolubara", "Velika Morava", "Drina"}, "Velika Morava"));
            dbHelper.addInitQuestion(new Question("Šta je bodorka?", new String[] {"Trava", "Riba", "Vrsta čamca", "Otrovna pečurka"}, "Riba"));
            dbHelper.addInitQuestion(new Question("Benjamin Disraeli je bio čuveni engleski?", new String[] {"Pisac", "Slikar", "Pronalazač", "Političar"}, "Političar"));
            dbHelper.addInitQuestion(new Question("U kom gradu se igralo finale Lige Šampiona u fudbalu 2009. godine?", new String[] {"Moskva", "Rim", "Atina", "Pariz"}, "Rim"));
            dbHelper.addInitQuestion(new Question("Koje godine je preminuo Nikola Tesla?", new String[] {"1945. godine", "1941. godine", "1943. godine", "1985. godine"}, "1943. godine"));
            dbHelper.addInitQuestion(new Question("Koje od ponuđenih mora ima najveću brzinu?", new String[] {"Egejsko", "Jadransko", "Jonsko", "Tirensko"}, "Jonsko"));
            dbHelper.addInitQuestion(new Question("Gde je rođena makedonska pevačica Kaliopi Bukle?", new String[] {"U Kičevu", "U Štipu", "U Gostivaru", "U Skoplju"}, "U Kičevu"));
            dbHelper.addInitQuestion(new Question("Koliko ima kičmenih pršljena?", new String[] {"35", "30", "33", "37"}, "33"));
            dbHelper.addInitQuestion(new Question("Koji fudbalski klub je proglašen za najbolji u XX veku?", new String[] {"Real Madrid", "Barcelona", "Juventus", "Manchester United"}, "Real Madrid"));
            dbHelper.addInitQuestion(new Question("Koji film je dobio Oskara za najbolji film 2007. godine?", new String[] {"Biće krvi", "Pokajanje", "Nema zemlje za strance", "Džuno"}, "Nema zemlje za strance"));
            dbHelper.addInitQuestion(new Question("Kom filozofu se pripisuje izreka 'Panta rei'?", new String[] {"Pitagora", "Anaksimen", "Parmenid", "Heraklit"}, "Heraklit"));
            dbHelper.addInitQuestion(new Question("Falco peregrinus je?", new String[] {"Orao", "Soko", "Jastreb", "Svraka"}, "Soko"));
            dbHelper.addInitQuestion(new Question("Trgovac na malo ili?", new String[] {"Krčman", "Šićardžija", "Bakalin", "Sitničar"}, "Bakalin"));
            dbHelper.addInitQuestion(new Question("Koja je najveća katolička zemlja na svetu?", new String[] {"Brazil", "Kanada", "Indonezija", "Venecuela"}, "Brazil"));
            dbHelper.addInitQuestion(new Question("Koja ptica je nacionalni simbol u Indiji?", new String[] {"Golub", "Lešinar", "Orao", "Paun"}, "Paun"));
            dbHelper.addInitQuestion(new Question("Koliko puta je muška reprezentacija Srbije bila prvak Evrope u odbojci do 2014. godine?", new String[] {"Dva puta", "Nisu osvojili", "Četiri puta", "Jednom"}, "Jednom"));
            dbHelper.addInitQuestion(new Question("Ko je napisao roman 'U potpaljublju'?", new String[] {"Dragoslav Mihajlović", "Vladimir Arsenijević", "Miroslav Josić-Višnjić", "Svetislav Basara"}, "Vladimir Arsenijević"));
            dbHelper.addInitQuestion(new Question("Radnja kog od navedenih filmova nije inspirisana istinitim događajem?", new String[] {"Forrest Gump", "Uhvati me ako možeš", "Osmi putnik", "Šindlerova lista"}, "Osmi putnik"));
            dbHelper.addInitQuestion(new Question("Blizu kog grada se odigrala bitka na Čegru?", new String[] {"Valjeva", "Čačka", "Niša", "Leskovca"}, "Niša"));
            dbHelper.addInitQuestion(new Question("Iz čijeg dela je lik Agaton?", new String[] {"Branislava Nušića", "Branka Ćopića", "Miloša Crnjanskog", "Antonija Isakovića"}, "Branislava Nušića"));
            dbHelper.addInitQuestion(new Question("Koji naš bokser je osvojio zlatnu medalju u Moskvi 1980. godine?", new String[] {"Marjan Beneš", "Slobodan Kačar", "Tadija Kačar", "Dragomir Vujković"}, "Slobodan Kačar"));
            dbHelper.addInitQuestion(new Question("Čije telo je uzeto kao model za Zvončicu u filmu 'Petar Pan'?", new String[] {"Vivien Leigh", "Audrey Hepburn", "Doris Day", "Marilyn Monroe"}, "Marilyn Monroe"));
            dbHelper.addInitQuestion(new Question("Koliko uglova ima deltoid?", new String[] {"Pet", "Četiri", "Dva", "Nula"}, "Četiri"));
            dbHelper.addInitQuestion(new Question("Ko je otkrio da je munja vrsta elektriciteta?", new String[] {"Benjamin Franklin", "Nikola Tesla", "Michael Faraday", "Alessandro Volta"}, "Benjamin Franklin"));
            dbHelper.addInitQuestion(new Question("Ko je prvi otkrio elektromagnetizam?", new String[] {"Nikola Tesla", "Hans Christian Ørsted", "Mihailo Pupin", "Thomas Edison"}, "Hans Christian Ørsted"));
            dbHelper.addInitQuestion(new Question("Kako su vezani električni uređaji u domaćinstvu u električnom kolu?", new String[] {"Paralelno", "Kružno", "Dijagonalno", "Polukružno"}, "Paralelno"));
            dbHelper.addInitQuestion(new Question("Koje je sveto drvo boga Peruna?", new String[] {"Lipa", "Kesten", "Hrast", "Platan"}, "Hrast"));
            dbHelper.addInitQuestion(new Question("Kako se zvao sveti bik Starih Egipana?", new String[] {"Antifat", "Jolaj", "Lucifer", "Apis"}, "Apis"));
            dbHelper.addInitQuestion(new Question("Koje dužine je bio Titanik?", new String[] {"261.1m","171.1m", "420.1m", "310.1m"}, "261.1m"));
            dbHelper.addInitQuestion(new Question("Ko je dobitnik Nobelove nagrade za književnost za 2012. godinu?", new String[] {"Herta Müller", "Orhan Pamuk", "Mo Yan", "Mario Vargas Llosa"}, "Mo Yan"));
            dbHelper.addInitQuestion(new Question("Kako se naziva obezvređivanje novca koje se ogleda u padu kupovne moći novca?", new String[] {"Disperzija", "Depresijacija", "Dividenda", "Duopol"}, "Depresijacija"));
            dbHelper.addInitQuestion(new Question("Pripovetka Ive Andrića je 'Aska i '?", new String[] {"Medved", "Lisica", "Veverica", "Vuk"}, "Vuk"));
            dbHelper.addInitQuestion(new Question("Telo se ravnomerno kretalo brzinom od 4 m/s. Koliko je kilometara prešlo ako se kretalo 25 sekundi?", new String[] {"0.1 km", "0.6 km", "1 km", "6 km"}, "0.1 km"));
            dbHelper.addInitQuestion(new Question("Ko od navedenih glumaca ne glumi u filmu 'Pretparačke priče' koji je režirao Quentin Tarantino?", new String[] {"Peter Green", "Michael Roberts", "Tim Roth", "Bruce Willis"}, "Michael Roberts"));
            dbHelper.addInitQuestion(new Question("Šta je po zanimanju Rus Евге́ний Ива́нович Замя́тин (Jevgenij Zamjatin)?", new String[] {"Slikar", "Baletan", "Pisac", "Kompozitor"}, "Pisac"));
            dbHelper.addInitQuestion(new Question("Kriks je?", new String[] {"Jadranski vetar", "Vrh na Kopaoniku", "Reka u Mađarskoj", "Podzemni vodotok"}, "Podzemni vodotok"));
            dbHelper.addInitQuestion(new Question("Koliko puta je pojavljuje cifra 9 u brojevima od 1 do 99?", new String[] {"20", "19", "11", "18"}, "20"));
            dbHelper.addInitQuestion(new Question("Šta znači izraz 'Pro bono'?", new String[] {"Svima jednako", "Profesionalni učinak", "Opšte dobro", "Kralju u čast"}, "Opšte dobro"));
            dbHelper.addInitQuestion(new Question("Koji deo teritorije Srbije nije pripadao tzv. 'Staroj Srbiji'?", new String[] {"Bosna i Hercegovina", "Sandžak", "Makedonija", "Kosovo i Metohija"}, "Bosna i Hercegovina"));
            dbHelper.addInitQuestion(new Question("Kada su u Srbiji uvedene obavezne metarske mere?", new String[] {"1850. godine", "1890. godine", "1880. godine", "1873. godine"}, "1873. godine"));
            dbHelper.addInitQuestion(new Question("Iz koje zemlje je čuveni astronom Christiaan Huygens?", new String[] {"Iz Nemačke", "Iz Holandije", "Iz Danske", "Iz Švedske"}, "Iz Holandije"));
            dbHelper.addInitQuestion(new Question("Šta označava reč 'alvaluk'?", new String[] {"Pijanicu", "Kolač", "Alavost", "Čast"}, "Čast"));
            dbHelper.addInitQuestion(new Question("'Mojsija' je izvajao?", new String[] {"Leonardo", "Donatelo", "Mikelanđelo", "Miron"}, "Mikelanđelo"));
            dbHelper.addInitQuestion(new Question("U kojoj disciplini je Franjo Mihalić osvojio srebrnu medalju na OI u Melburnu 1956. godine?", new String[] {"Brzom hodanju", "10.000 metara", "Višeboju", "Maratonu"}, "Maratonu"));
            dbHelper.addInitQuestion(new Question("Kada je stvorena država Albanija?", new String[] {"1801. godine", "1921. godine", "1614. godine", "1713. godine"}, "1921. godine"));
            dbHelper.addInitQuestion(new Question("Otto Heinrich Warburg je bio nemački?", new String[] {"Astronom", "Inženjer", "Biolog", "Industrijalac"}, "Biolog"));
            dbHelper.addInitQuestion(new Question("Šta su partikule?", new String[] {"Rečce", "Prilozi", "Uzvici", "Veznici"}, "Rečce"));
            dbHelper.addInitQuestion(new Question("Njegovo pravo ime je Jacopo Robusti, a on je?", new String[] {"Karavađo", "Rafael", "Tintoreto", "Donatelo"}, "Tintoreto"));
            dbHelper.addInitQuestion(new Question("Ko igra glavnu ulogu u filmu 'Alpinista'?", new String[] {"Sylvester Stallone", "Robert De Niro", "Tom Cruise", "Matthew McConaughey"}, "Sylvester Stallone"));
            dbHelper.addInitQuestion(new Question("U romanu 'Seobe' Miloš Crnjanski je opisao deo istorije porodice?", new String[] {"Katić", "Garašanin", "Dunđerski", "Isaković"}, "Isaković"));
            dbHelper.addInitQuestion(new Question("Kako se naziva duž koja spaja dve tačke na kružnici?", new String[] {"Euklida", "Tetiva", "Direktrisa", "Tangenta"}, "Tetiva"));
            dbHelper.addInitQuestion(new Question("Hologram je?", new String[] {"Astronomska mapa", "Šifrovana poruka", "Trodimenzionalna slika", "Štampano platno"}, "Trodimenzionalna slika"));
            dbHelper.addInitQuestion(new Question("Ko glumi Daenerys Targaryen u seriji 'Igra prestola'?", new String[] {"Julia Roberts", "Lena Headey", "Sandra Bullock", "Emilia Clarke"}, "Emilia Clarke"));
            dbHelper.addInitQuestion(new Question("Koga je ubio Jack Ruby?", new String[] {"Džona Kenedija", "Li Harvi Osvalda", "Džona Lenona", "Marka Čepmena"},"Li Harvi Osvalda"));
            dbHelper.addInitQuestion(new Question("Koji grad Nemci nazivaju Lajbah?", new String[] {"Budimpeštu", "Zagreb", "Skopje", "Ljubljanu"}, "Ljubljanu"));
            dbHelper.addInitQuestion(new Question("Gde je nastala Gotika?", new String[] {"U Italiji", "U Francuskoj", "U Nemačkoj", "U Engleskoj"}, "U Francuskoj"));
            dbHelper.addInitQuestion(new Question("U kom veku je otvoren muzej Luvr?", new String[] {"XX", "XIX", "XVIII", "XVII"}, "XVIII"));
            dbHelper.addInitQuestion(new Question("Koje godine je srpska vojska došla na Solunski front?", new String[] {"1915.", "1916.", "1917.", "1918."}, "1916."));
            dbHelper.addInitQuestion(new Question("Ko je Rodion Raskoljnikov?", new String[] {"Ruski atletičar", "Junak romana 'Zločin i kazna'", "Ruski baletan", "Beloruski atletičar"}, "Junak romana 'Zločin i kazna'"));
            dbHelper.addInitQuestion(new Question("Čang Kaj Šek je vodio veliku borbu protiv?", new String[] {"Indije", "Nepala", "Tajvana", "Komunističke partije Kine"}, "Komunističke partije Kine"));
            dbHelper.addInitQuestion(new Question("Koji film Darka Bajića opisuje odnose između tajnih službi o bivšoj Jugoslaviji?", new String[] {"Balkanska pravila", "Bure baruta", "Hajka", "Početni udarac"}, "Balkanska pravila"));
            dbHelper.addInitQuestion(new Question("Reč atoksičan označava da nešto nije?", new String[] {"Okruglo", "Kiselo", "Veliko", "Otrovno"}, "Otrovno"));
            dbHelper.addInitQuestion(new Question("Kroz koji grad protiče reka Sava?", new String[] {"Valjevo", "Šabac", "Loznicu", "Požarevac"}, "Šabac"));
            dbHelper.addInitQuestion(new Question("Iz koje zemlje je afrički pevač i gitarista Ali Farka Ture?", new String[] {"Iz Obale Slonovače", "Iz Nigerije", "Iz Senegala", "Iz Malija"}, "Iz Malija"));
            dbHelper.addInitQuestion(new Question("Ko je režirao seriju 'Čista Hemija'?", new String[] {"Vins Giligen", " Danijel Sakhajm", "Paul Scheuring", "Tim Van Patten"}, "Vins Giligen"));
            dbHelper.addInitQuestion(new Question("Kako se zvao jedan od najboljih italijanskih biciklista u brdskim etapama, a čiji je nadimak bio Gusar?", new String[] {"Paolo Betini", "Ivan Baso", "Marko Pantani", "Fabricio Maki"}, "Fabricio Maki"));
            dbHelper.addInitQuestion(new Question("Koliko godina je imao Nebojša Glogovac kada je preminuo?", new String[] {"48", "52", "50", "46"}, "48"));
            dbHelper.addInitQuestion(new Question("Koji je najveći grad i centar Tibeta?", new String[] {"Lamanos", "Larma", "Lasa", "Lama"}, "Lasa"));
            dbHelper.addInitQuestion(new Question("Šta označava slovo R u reči laser?", new String[] {"Razaranje", "Redmond", "Radijaciju", "Rezistenciju"}, "Radijaciju"));
            dbHelper.addInitQuestion(new Question("Gde žive koale?", new String[] {"U Americi", "U Aziji", "U Evropi", "U Australiji"}, "U Australiji"));
            dbHelper.addInitQuestion(new Question("Koji od ponuđenih gradova u Hrvatskoj je najseverniji?", new String[] {"Pazin", "Čakovec", "Rijeka", "Zagreb"}, "Čakovec"));
            dbHelper.addInitQuestion(new Question("Ko je komponovao operu 'Boris Godunov'?", new String[] {"Nikolai Rimsky-Korsakov", "Bedřich Smetana", "Pyotr Ilyich Tchaikovsky", "Modest Mussorgsky"}, "Modest Mussorgsky"));
            dbHelper.addInitQuestion(new Question("Koliko je potrebno Mesecu da obiđe oko Sunca?", new String[] {"Pola godine", "28 dana", "Godinu dana", "12 nedelja"}, "Godinu dana"));
            dbHelper.addInitQuestion(new Question("'Od izvora dva putića' peva?", new String[] {"Biljana Jevtić", "Lepa Lukić", "Snežana Đurišić", "Ana Bekuta"}, "Lepa Lukić"));
            dbHelper.addInitQuestion(new Question("Ko ne spada u tzv. bečke klasičare?", new String[] {"Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Franz Joseph Haydn", "Ludwig van Beethoven"}, "Johann Sebastian Bach"));
            dbHelper.addInitQuestion(new Question("Rejkjavik je glavni grad?", new String[] {"Irske", "Moldavije", "Islanda", "Grenlanda"}, "Islanda"));
            dbHelper.addInitQuestion(new Question("Ko je bio najbolji strelac SP u fudbalu 1930. godine u Urugvaju?", new String[] {"Aleksandar Tirnanić Tirke", "Giljermo Stabile", "Luis Monti", "Santos Iriante"}, "Giljermo Stabile"));
            dbHelper.addInitQuestion(new Question("Koji muzički instrument je 'Hamond'?", new String[] {"Harfa", "Violina", "Harmonika", "Orgulje"}, "Orgulje"));
            dbHelper.addInitQuestion(new Question("U kojoj aferi je učestvovao Nikson?", new String[] {"Votergejt", "Simpson", "Vijetkong", "Staviski"}, "Votergejt"));
            dbHelper.addInitQuestion(new Question("'Pinc' je vrsta?", new String[] {"Vojnog vozila", "Torte", "Ruže", "Vina"}, "Vojnog vozila"));
            dbHelper.addInitQuestion(new Question("Koji je pozivni broj policije u Srbiji?", new String[] {"193", "195", "192", "194"}, "192"));
            dbHelper.addInitQuestion(new Question("Motet je?", new String[] {"Pravac u Baroku", "Forma vokalne muzike", "Muzički instrument", "Dirigentska palica"}, "Forma vokalne muzike"));
            dbHelper.addInitQuestion(new Question("Koji je nadimak strip junaka Zagora?", new String[] {"Duh koji hoda", "Duh sa testerom", "Duh iz Darkvuda", "Duh sa sekirom"}, "Duh sa sekirom"));
            dbHelper.addInitQuestion(new Question("U kom od navedenih filmova ne glumi Julia Roberts?", new String[] {"Runaway Bride", "Shine", "Mystic Pizza", "Erin Brockovich"}, "Shine"));

            list = dbHelper.getAllQuestions();
        }

    }


}
